# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fgoMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fgoMainWindow(object):
    def setupUi(self, fgoMainWindow):
        fgoMainWindow.setObjectName("fgoMainWindow")
        fgoMainWindow.resize(493, 455)
        self.widget = QtWidgets.QWidget(fgoMainWindow)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LAYOUT_PARTY = QtWidgets.QHBoxLayout()
        self.LAYOUT_PARTY.setObjectName("LAYOUT_PARTY")
        self.CBX_PARTY = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CBX_PARTY.sizePolicy().hasHeightForWidth())
        self.CBX_PARTY.setSizePolicy(sizePolicy)
        self.CBX_PARTY.setObjectName("CBX_PARTY")
        self.LAYOUT_PARTY.addWidget(self.CBX_PARTY)
        self.BTN_PARTYSAVE = QtWidgets.QPushButton(self.widget)
        self.BTN_PARTYSAVE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_PARTYSAVE.setObjectName("BTN_PARTYSAVE")
        self.LAYOUT_PARTY.addWidget(self.BTN_PARTYSAVE)
        self.BTN_PARTYRESET = QtWidgets.QPushButton(self.widget)
        self.BTN_PARTYRESET.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_PARTYRESET.setObjectName("BTN_PARTYRESET")
        self.LAYOUT_PARTY.addWidget(self.BTN_PARTYRESET)
        self.verticalLayout.addLayout(self.LAYOUT_PARTY)
        self.LAYOUT_INFO = QtWidgets.QFormLayout()
        self.LAYOUT_INFO.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.LAYOUT_INFO.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LAYOUT_INFO.setObjectName("LAYOUT_INFO")
        self.LBL_SKILLINFO = QtWidgets.QLabel(self.widget)
        self.LBL_SKILLINFO.setObjectName("LBL_SKILLINFO")
        self.LAYOUT_INFO.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LBL_SKILLINFO)
        self.LAYOUT_INFO_PARTY = QtWidgets.QFormLayout()
        self.LAYOUT_INFO_PARTY.setObjectName("LAYOUT_INFO_PARTY")
        self.LBL_PARTY_0 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_0.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_0.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_0.setObjectName("LBL_PARTY_0")
        self.LAYOUT_INFO_PARTY.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_0)
        self.LAYOUT_INFO_PARTY_0 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_0.setObjectName("LAYOUT_INFO_PARTY_0")
        self.RBT_FRIEND_0 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_0.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_0.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_0.setText("")
        self.RBT_FRIEND_0.setObjectName("RBT_FRIEND_0")
        self.BTG_FRIEND = QtWidgets.QButtonGroup(fgoMainWindow)
        self.BTG_FRIEND.setObjectName("BTG_FRIEND")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_0)
        self.LAYOUT_INFO_PARTY_0.addWidget(self.RBT_FRIEND_0)
        self.TXT_SKILL_0_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_0.setMaxLength(1)
        self.TXT_SKILL_0_0_0.setObjectName("TXT_SKILL_0_0_0")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_0_0)
        self.TXT_SKILL_0_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_1.setMaxLength(1)
        self.TXT_SKILL_0_0_1.setObjectName("TXT_SKILL_0_0_1")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_0_1)
        self.TXT_SKILL_0_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_2.setMaxLength(1)
        self.TXT_SKILL_0_0_2.setObjectName("TXT_SKILL_0_0_2")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_0_2)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_0.addItem(spacerItem)
        self.TXT_SKILL_0_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_0.setMaxLength(1)
        self.TXT_SKILL_0_1_0.setObjectName("TXT_SKILL_0_1_0")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_1_0)
        self.TXT_SKILL_0_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_1.setMaxLength(1)
        self.TXT_SKILL_0_1_1.setObjectName("TXT_SKILL_0_1_1")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_1_1)
        self.TXT_SKILL_0_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_2.setMaxLength(1)
        self.TXT_SKILL_0_1_2.setObjectName("TXT_SKILL_0_1_2")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_1_2)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_0.addItem(spacerItem1)
        self.TXT_SKILL_0_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_0.setMaxLength(1)
        self.TXT_SKILL_0_2_0.setObjectName("TXT_SKILL_0_2_0")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_2_0)
        self.TXT_SKILL_0_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_1.setMaxLength(1)
        self.TXT_SKILL_0_2_1.setObjectName("TXT_SKILL_0_2_1")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_2_1)
        self.TXT_SKILL_0_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_2.setMaxLength(1)
        self.TXT_SKILL_0_2_2.setObjectName("TXT_SKILL_0_2_2")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_2_2)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_0.addItem(spacerItem2)
        self.TXT_HOUGU_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_0.setMaxLength(1)
        self.TXT_HOUGU_0_0.setObjectName("TXT_HOUGU_0_0")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_HOUGU_0_0)
        self.TXT_HOUGU_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_1.setMaxLength(1)
        self.TXT_HOUGU_0_1.setObjectName("TXT_HOUGU_0_1")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_HOUGU_0_1)
        self.LAYOUT_INFO_PARTY.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_0)
        self.LBL_PARTY_1 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_1.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_1.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_1.setObjectName("LBL_PARTY_1")
        self.LAYOUT_INFO_PARTY.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_1)
        self.LAYOUT_INFO_PARTY_1 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_1.setObjectName("LAYOUT_INFO_PARTY_1")
        self.RBT_FRIEND_1 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_1.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_1.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_1.setText("")
        self.RBT_FRIEND_1.setObjectName("RBT_FRIEND_1")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_1)
        self.LAYOUT_INFO_PARTY_1.addWidget(self.RBT_FRIEND_1)
        self.TXT_SKILL_1_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_0.setMaxLength(1)
        self.TXT_SKILL_1_0_0.setObjectName("TXT_SKILL_1_0_0")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_0_0)
        self.TXT_SKILL_1_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_1.setMaxLength(1)
        self.TXT_SKILL_1_0_1.setObjectName("TXT_SKILL_1_0_1")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_0_1)
        self.TXT_SKILL_1_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_2.setMaxLength(1)
        self.TXT_SKILL_1_0_2.setObjectName("TXT_SKILL_1_0_2")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_0_2)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_1.addItem(spacerItem3)
        self.TXT_SKILL_1_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_0.setMaxLength(1)
        self.TXT_SKILL_1_1_0.setObjectName("TXT_SKILL_1_1_0")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_1_0)
        self.TXT_SKILL_1_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_1.setMaxLength(1)
        self.TXT_SKILL_1_1_1.setObjectName("TXT_SKILL_1_1_1")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_1_1)
        self.TXT_SKILL_1_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_2.setMaxLength(1)
        self.TXT_SKILL_1_1_2.setObjectName("TXT_SKILL_1_1_2")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_1_2)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_1.addItem(spacerItem4)
        self.TXT_SKILL_1_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_0.setMaxLength(1)
        self.TXT_SKILL_1_2_0.setObjectName("TXT_SKILL_1_2_0")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_2_0)
        self.TXT_SKILL_1_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_1.setMaxLength(1)
        self.TXT_SKILL_1_2_1.setObjectName("TXT_SKILL_1_2_1")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_2_1)
        self.TXT_SKILL_1_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_2.setMaxLength(1)
        self.TXT_SKILL_1_2_2.setObjectName("TXT_SKILL_1_2_2")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_2_2)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_1.addItem(spacerItem5)
        self.TXT_HOUGU_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_0.setMaxLength(1)
        self.TXT_HOUGU_1_0.setObjectName("TXT_HOUGU_1_0")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_HOUGU_1_0)
        self.TXT_HOUGU_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_1.setMaxLength(1)
        self.TXT_HOUGU_1_1.setObjectName("TXT_HOUGU_1_1")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_HOUGU_1_1)
        self.LAYOUT_INFO_PARTY.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_1)
        self.LBL_PARTY_2 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_2.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_2.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_2.setObjectName("LBL_PARTY_2")
        self.LAYOUT_INFO_PARTY.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_2)
        self.LAYOUT_INFO_PARTY_2 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_2.setObjectName("LAYOUT_INFO_PARTY_2")
        self.RBT_FRIEND_2 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_2.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_2.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_2.setText("")
        self.RBT_FRIEND_2.setObjectName("RBT_FRIEND_2")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_2)
        self.LAYOUT_INFO_PARTY_2.addWidget(self.RBT_FRIEND_2)
        self.TXT_SKILL_2_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_0.setMaxLength(1)
        self.TXT_SKILL_2_0_0.setObjectName("TXT_SKILL_2_0_0")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_0_0)
        self.TXT_SKILL_2_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_1.setMaxLength(1)
        self.TXT_SKILL_2_0_1.setObjectName("TXT_SKILL_2_0_1")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_0_1)
        self.TXT_SKILL_2_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_2.setMaxLength(1)
        self.TXT_SKILL_2_0_2.setObjectName("TXT_SKILL_2_0_2")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_0_2)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_2.addItem(spacerItem6)
        self.TXT_SKILL_2_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_0.setMaxLength(1)
        self.TXT_SKILL_2_1_0.setObjectName("TXT_SKILL_2_1_0")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_1_0)
        self.TXT_SKILL_2_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_1.setMaxLength(1)
        self.TXT_SKILL_2_1_1.setObjectName("TXT_SKILL_2_1_1")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_1_1)
        self.TXT_SKILL_2_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_2.setMaxLength(1)
        self.TXT_SKILL_2_1_2.setObjectName("TXT_SKILL_2_1_2")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_1_2)
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_2.addItem(spacerItem7)
        self.TXT_SKILL_2_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_0.setMaxLength(1)
        self.TXT_SKILL_2_2_0.setObjectName("TXT_SKILL_2_2_0")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_2_0)
        self.TXT_SKILL_2_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_1.setMaxLength(1)
        self.TXT_SKILL_2_2_1.setObjectName("TXT_SKILL_2_2_1")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_2_1)
        self.TXT_SKILL_2_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_2.setMaxLength(1)
        self.TXT_SKILL_2_2_2.setObjectName("TXT_SKILL_2_2_2")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_2_2)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_2.addItem(spacerItem8)
        self.TXT_HOUGU_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_0.setMaxLength(1)
        self.TXT_HOUGU_2_0.setObjectName("TXT_HOUGU_2_0")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_HOUGU_2_0)
        self.TXT_HOUGU_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_1.setMaxLength(1)
        self.TXT_HOUGU_2_1.setObjectName("TXT_HOUGU_2_1")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_HOUGU_2_1)
        self.LAYOUT_INFO_PARTY.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_2)
        self.LBL_PARTY_3 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_3.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_3.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_3.setObjectName("LBL_PARTY_3")
        self.LAYOUT_INFO_PARTY.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_3)
        self.LAYOUT_INFO_PARTY_3 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_3.setObjectName("LAYOUT_INFO_PARTY_3")
        self.RBT_FRIEND_3 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_3.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_3.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_3.setText("")
        self.RBT_FRIEND_3.setObjectName("RBT_FRIEND_3")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_3)
        self.LAYOUT_INFO_PARTY_3.addWidget(self.RBT_FRIEND_3)
        self.TXT_SKILL_3_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_0.setMaxLength(1)
        self.TXT_SKILL_3_0_0.setObjectName("TXT_SKILL_3_0_0")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_0_0)
        self.TXT_SKILL_3_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_1.setMaxLength(1)
        self.TXT_SKILL_3_0_1.setObjectName("TXT_SKILL_3_0_1")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_0_1)
        self.TXT_SKILL_3_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_2.setMaxLength(1)
        self.TXT_SKILL_3_0_2.setObjectName("TXT_SKILL_3_0_2")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_0_2)
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_3.addItem(spacerItem9)
        self.TXT_SKILL_3_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_0.setMaxLength(1)
        self.TXT_SKILL_3_1_0.setObjectName("TXT_SKILL_3_1_0")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_1_0)
        self.TXT_SKILL_3_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_1.setMaxLength(1)
        self.TXT_SKILL_3_1_1.setObjectName("TXT_SKILL_3_1_1")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_1_1)
        self.TXT_SKILL_3_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_2.setMaxLength(1)
        self.TXT_SKILL_3_1_2.setObjectName("TXT_SKILL_3_1_2")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_1_2)
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_3.addItem(spacerItem10)
        self.TXT_SKILL_3_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_0.setMaxLength(1)
        self.TXT_SKILL_3_2_0.setObjectName("TXT_SKILL_3_2_0")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_2_0)
        self.TXT_SKILL_3_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_1.setMaxLength(1)
        self.TXT_SKILL_3_2_1.setObjectName("TXT_SKILL_3_2_1")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_2_1)
        self.TXT_SKILL_3_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_2.setMaxLength(1)
        self.TXT_SKILL_3_2_2.setObjectName("TXT_SKILL_3_2_2")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_2_2)
        spacerItem11 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_3.addItem(spacerItem11)
        self.TXT_HOUGU_3_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_3_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_0.setMaxLength(1)
        self.TXT_HOUGU_3_0.setObjectName("TXT_HOUGU_3_0")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_HOUGU_3_0)
        self.TXT_HOUGU_3_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_3_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_1.setMaxLength(1)
        self.TXT_HOUGU_3_1.setObjectName("TXT_HOUGU_3_1")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_HOUGU_3_1)
        self.LAYOUT_INFO_PARTY.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_3)
        self.LBL_PARTY_4 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_4.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_4.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_4.setObjectName("LBL_PARTY_4")
        self.LAYOUT_INFO_PARTY.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_4)
        self.LAYOUT_INFO_PARTY_4 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_4.setObjectName("LAYOUT_INFO_PARTY_4")
        self.RBT_FRIEND_4 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_4.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_4.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBT_FRIEND_4.setText("")
        self.RBT_FRIEND_4.setChecked(True)
        self.RBT_FRIEND_4.setObjectName("RBT_FRIEND_4")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_4)
        self.LAYOUT_INFO_PARTY_4.addWidget(self.RBT_FRIEND_4)
        self.TXT_SKILL_4_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_0.setMaxLength(1)
        self.TXT_SKILL_4_0_0.setObjectName("TXT_SKILL_4_0_0")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_0_0)
        self.TXT_SKILL_4_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_1.setMaxLength(1)
        self.TXT_SKILL_4_0_1.setObjectName("TXT_SKILL_4_0_1")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_0_1)
        self.TXT_SKILL_4_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_2.setMaxLength(1)
        self.TXT_SKILL_4_0_2.setObjectName("TXT_SKILL_4_0_2")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_0_2)
        spacerItem12 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_4.addItem(spacerItem12)
        self.TXT_SKILL_4_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_0.setMaxLength(1)
        self.TXT_SKILL_4_1_0.setObjectName("TXT_SKILL_4_1_0")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_1_0)
        self.TXT_SKILL_4_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_1.setMaxLength(1)
        self.TXT_SKILL_4_1_1.setObjectName("TXT_SKILL_4_1_1")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_1_1)
        self.TXT_SKILL_4_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_2.setMaxLength(1)
        self.TXT_SKILL_4_1_2.setObjectName("TXT_SKILL_4_1_2")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_1_2)
        spacerItem13 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_4.addItem(spacerItem13)
        self.TXT_SKILL_4_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_0.setMaxLength(1)
        self.TXT_SKILL_4_2_0.setObjectName("TXT_SKILL_4_2_0")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_2_0)
        self.TXT_SKILL_4_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_1.setMaxLength(1)
        self.TXT_SKILL_4_2_1.setObjectName("TXT_SKILL_4_2_1")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_2_1)
        self.TXT_SKILL_4_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_2.setMaxLength(1)
        self.TXT_SKILL_4_2_2.setObjectName("TXT_SKILL_4_2_2")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_2_2)
        spacerItem14 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_4.addItem(spacerItem14)
        self.TXT_HOUGU_4_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_4_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_0.setMaxLength(1)
        self.TXT_HOUGU_4_0.setObjectName("TXT_HOUGU_4_0")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_HOUGU_4_0)
        self.TXT_HOUGU_4_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_4_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_1.setMaxLength(1)
        self.TXT_HOUGU_4_1.setObjectName("TXT_HOUGU_4_1")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_HOUGU_4_1)
        self.LAYOUT_INFO_PARTY.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_4)
        self.LBL_PARTY_5 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_5.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_5.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_5.setObjectName("LBL_PARTY_5")
        self.LAYOUT_INFO_PARTY.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_5)
        self.LAYOUT_INFO_PARTY_5 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_5.setObjectName("LAYOUT_INFO_PARTY_5")
        self.RBT_FRIEND_5 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_5.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_5.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_5.setText("")
        self.RBT_FRIEND_5.setChecked(False)
        self.RBT_FRIEND_5.setObjectName("RBT_FRIEND_5")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_5)
        self.LAYOUT_INFO_PARTY_5.addWidget(self.RBT_FRIEND_5)
        self.TXT_SKILL_5_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_0.setMaxLength(1)
        self.TXT_SKILL_5_0_0.setObjectName("TXT_SKILL_5_0_0")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_0_0)
        self.TXT_SKILL_5_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_1.setMaxLength(1)
        self.TXT_SKILL_5_0_1.setObjectName("TXT_SKILL_5_0_1")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_0_1)
        self.TXT_SKILL_5_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_2.setMaxLength(1)
        self.TXT_SKILL_5_0_2.setObjectName("TXT_SKILL_5_0_2")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_0_2)
        spacerItem15 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_5.addItem(spacerItem15)
        self.TXT_SKILL_5_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_0.setMaxLength(1)
        self.TXT_SKILL_5_1_0.setObjectName("TXT_SKILL_5_1_0")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_1_0)
        self.TXT_SKILL_5_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_1.setMaxLength(1)
        self.TXT_SKILL_5_1_1.setObjectName("TXT_SKILL_5_1_1")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_1_1)
        self.TXT_SKILL_5_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_2.setMaxLength(1)
        self.TXT_SKILL_5_1_2.setObjectName("TXT_SKILL_5_1_2")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_1_2)
        spacerItem16 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_5.addItem(spacerItem16)
        self.TXT_SKILL_5_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_0.setMaxLength(1)
        self.TXT_SKILL_5_2_0.setObjectName("TXT_SKILL_5_2_0")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_2_0)
        self.TXT_SKILL_5_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_1.setMaxLength(1)
        self.TXT_SKILL_5_2_1.setObjectName("TXT_SKILL_5_2_1")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_2_1)
        self.TXT_SKILL_5_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_2.setMaxLength(1)
        self.TXT_SKILL_5_2_2.setObjectName("TXT_SKILL_5_2_2")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_2_2)
        spacerItem17 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_5.addItem(spacerItem17)
        self.TXT_HOUGU_5_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_5_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_0.setMaxLength(1)
        self.TXT_HOUGU_5_0.setObjectName("TXT_HOUGU_5_0")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_HOUGU_5_0)
        self.TXT_HOUGU_5_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_5_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_1.setMaxLength(1)
        self.TXT_HOUGU_5_1.setObjectName("TXT_HOUGU_5_1")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_HOUGU_5_1)
        self.LAYOUT_INFO_PARTY.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_5)
        self.LAYOUT_INFO.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY)
        self.LBL_DANGERPOS = QtWidgets.QLabel(self.widget)
        self.LBL_DANGERPOS.setObjectName("LBL_DANGERPOS")
        self.LAYOUT_INFO.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LBL_DANGERPOS)
        self.LAYOUT_INFO_DANGER = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_DANGER.setObjectName("LAYOUT_INFO_DANGER")
        self.TXT_DANGER_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_DANGER_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_0.setMaxLength(1)
        self.TXT_DANGER_0.setObjectName("TXT_DANGER_0")
        self.LAYOUT_INFO_DANGER.addWidget(self.TXT_DANGER_0)
        spacerItem18 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_DANGER.addItem(spacerItem18)
        self.TXT_DANGER_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_DANGER_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_1.setMaxLength(1)
        self.TXT_DANGER_1.setObjectName("TXT_DANGER_1")
        self.LAYOUT_INFO_DANGER.addWidget(self.TXT_DANGER_1)
        spacerItem19 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_DANGER.addItem(spacerItem19)
        self.TXT_DANGER_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_DANGER_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_2.setMaxLength(1)
        self.TXT_DANGER_2.setObjectName("TXT_DANGER_2")
        self.LAYOUT_INFO_DANGER.addWidget(self.TXT_DANGER_2)
        self.LAYOUT_INFO.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_DANGER)
        self.LBL_APPLE = QtWidgets.QLabel(self.widget)
        self.LBL_APPLE.setObjectName("LBL_APPLE")
        self.LAYOUT_INFO.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LBL_APPLE)
        self.LAYOUT_INFO_APPLE = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_APPLE.setObjectName("LAYOUT_INFO_APPLE")
        self.CBX_APPLE = QtWidgets.QComboBox(self.widget)
        self.CBX_APPLE.setObjectName("CBX_APPLE")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.LAYOUT_INFO_APPLE.addWidget(self.CBX_APPLE)
        self.TXT_APPLE = QtWidgets.QLineEdit(self.widget)
        self.TXT_APPLE.setMaxLength(10)
        self.TXT_APPLE.setObjectName("TXT_APPLE")
        self.LAYOUT_INFO_APPLE.addWidget(self.TXT_APPLE)
        self.LAYOUT_INFO.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_APPLE)
        self.verticalLayout.addLayout(self.LAYOUT_INFO)
        self.LAYOUT_FUNC = QtWidgets.QHBoxLayout()
        self.LAYOUT_FUNC.setObjectName("LAYOUT_FUNC")
        self.LAYOUT_FUNC_ANDROID = QtWidgets.QVBoxLayout()
        self.LAYOUT_FUNC_ANDROID.setObjectName("LAYOUT_FUNC_ANDROID")
        self.BTN_GETDEVICE = QtWidgets.QPushButton(self.widget)
        self.BTN_GETDEVICE.setObjectName("BTN_GETDEVICE")
        self.LAYOUT_FUNC_ANDROID.addWidget(self.BTN_GETDEVICE)
        self.BTN_ADBCONNECT = QtWidgets.QPushButton(self.widget)
        self.BTN_ADBCONNECT.setObjectName("BTN_ADBCONNECT")
        self.LAYOUT_FUNC_ANDROID.addWidget(self.BTN_ADBCONNECT)
        self.LAYOUT_FUNC.addLayout(self.LAYOUT_FUNC_ANDROID)
        self.LAYOUT_FUNC_WIN = QtWidgets.QVBoxLayout()
        self.LAYOUT_FUNC_WIN.setObjectName("LAYOUT_FUNC_WIN")
        self.BTN_GETHWND = QtWidgets.QPushButton(self.widget)
        self.BTN_GETHWND.setEnabled(True)
        self.BTN_GETHWND.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_GETHWND.setObjectName("BTN_GETHWND")
        self.LAYOUT_FUNC_WIN.addWidget(self.BTN_GETHWND)
        self.BTN_CHECK = QtWidgets.QPushButton(self.widget)
        self.BTN_CHECK.setEnabled(True)
        self.BTN_CHECK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_CHECK.setObjectName("BTN_CHECK")
        self.LAYOUT_FUNC_WIN.addWidget(self.BTN_CHECK)
        self.BTN_GETFRIEND = QtWidgets.QPushButton(self.widget)
        self.BTN_GETFRIEND.setObjectName("BTN_GETFRIEND")
        self.LAYOUT_FUNC_WIN.addWidget(self.BTN_GETFRIEND)
        self.LAYOUT_FUNC.addLayout(self.LAYOUT_FUNC_WIN)
        self.LAYOUT_FUNC_MAIN = QtWidgets.QVBoxLayout()
        self.LAYOUT_FUNC_MAIN.setObjectName("LAYOUT_FUNC_MAIN")
        self.BTN_DRAW = QtWidgets.QPushButton(self.widget)
        self.BTN_DRAW.setEnabled(False)
        self.BTN_DRAW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_DRAW.setObjectName("BTN_DRAW")
        self.LAYOUT_FUNC_MAIN.addWidget(self.BTN_DRAW)
        self.BTN_ONEBATTLE = QtWidgets.QPushButton(self.widget)
        self.BTN_ONEBATTLE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_ONEBATTLE.setObjectName("BTN_ONEBATTLE")
        self.LAYOUT_FUNC_MAIN.addWidget(self.BTN_ONEBATTLE)
        self.BTN_MAIN = QtWidgets.QPushButton(self.widget)
        self.BTN_MAIN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_MAIN.setObjectName("BTN_MAIN")
        self.LAYOUT_FUNC_MAIN.addWidget(self.BTN_MAIN)
        self.LAYOUT_FUNC.addLayout(self.LAYOUT_FUNC_MAIN)
        self.LAYOUT_FUNC_CONTROL = QtWidgets.QVBoxLayout()
        self.LAYOUT_FUNC_CONTROL.setObjectName("LAYOUT_FUNC_CONTROL")
        self.BTN_PAUSE = QtWidgets.QPushButton(self.widget)
        self.BTN_PAUSE.setEnabled(False)
        self.BTN_PAUSE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_PAUSE.setObjectName("BTN_PAUSE")
        self.LAYOUT_FUNC_CONTROL.addWidget(self.BTN_PAUSE)
        self.BTN_STOP = QtWidgets.QPushButton(self.widget)
        self.BTN_STOP.setEnabled(False)
        self.BTN_STOP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_STOP.setObjectName("BTN_STOP")
        self.LAYOUT_FUNC_CONTROL.addWidget(self.BTN_STOP)
        self.LAYOUT_FUNC.addLayout(self.LAYOUT_FUNC_CONTROL)
        self.verticalLayout.addLayout(self.LAYOUT_FUNC)
        fgoMainWindow.setCentralWidget(self.widget)
        self.menuBar = QtWidgets.QMenuBar(fgoMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 493, 26))
        self.menuBar.setObjectName("menuBar")
        self.MENU_ABOUT = QtWidgets.QMenu(self.menuBar)
        self.MENU_ABOUT.setObjectName("MENU_ABOUT")
        fgoMainWindow.setMenuBar(self.menuBar)
        self.MENU_ABOUT_UNDEFINED = QtWidgets.QAction(fgoMainWindow)
        self.MENU_ABOUT_UNDEFINED.setObjectName("MENU_ABOUT_UNDEFINED")
        self.MENU_ABOUT.addAction(self.MENU_ABOUT_UNDEFINED)
        self.menuBar.addAction(self.MENU_ABOUT.menuAction())

        self.retranslateUi(fgoMainWindow)
        self.CBX_APPLE.setCurrentIndex(0)
        self.BTN_ONEBATTLE.clicked.connect(fgoMainWindow.runOneBattle)
        self.BTN_MAIN.clicked.connect(fgoMainWindow.runMain)
        self.BTN_CHECK.clicked.connect(fgoMainWindow.checkCheck)
        self.BTN_GETHWND.clicked.connect(fgoMainWindow.getHwnd)
        self.BTN_PAUSE.clicked.connect(fgoMainWindow.pause)
        self.BTN_STOP.clicked.connect(fgoMainWindow.stop)
        self.CBX_PARTY.activated['QString'].connect(fgoMainWindow.loadParty)
        self.BTN_PARTYSAVE.clicked.connect(fgoMainWindow.saveParty)
        self.BTN_PARTYRESET.clicked.connect(fgoMainWindow.resetParty)
        self.BTN_GETFRIEND.clicked.connect(fgoMainWindow.getFriend)
        self.BTN_GETDEVICE.clicked.connect(fgoMainWindow.getDevice)
        self.BTN_ADBCONNECT.clicked.connect(fgoMainWindow.adbConnect)
        QtCore.QMetaObject.connectSlotsByName(fgoMainWindow)
        fgoMainWindow.setTabOrder(self.CBX_PARTY, self.BTN_PARTYSAVE)
        fgoMainWindow.setTabOrder(self.BTN_PARTYSAVE, self.BTN_PARTYRESET)
        fgoMainWindow.setTabOrder(self.BTN_PARTYRESET, self.RBT_FRIEND_0)
        fgoMainWindow.setTabOrder(self.RBT_FRIEND_0, self.RBT_FRIEND_1)
        fgoMainWindow.setTabOrder(self.RBT_FRIEND_1, self.RBT_FRIEND_2)
        fgoMainWindow.setTabOrder(self.RBT_FRIEND_2, self.RBT_FRIEND_3)
        fgoMainWindow.setTabOrder(self.RBT_FRIEND_3, self.RBT_FRIEND_4)
        fgoMainWindow.setTabOrder(self.RBT_FRIEND_4, self.RBT_FRIEND_5)
        fgoMainWindow.setTabOrder(self.RBT_FRIEND_5, self.TXT_SKILL_0_0_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_0_0, self.TXT_SKILL_0_0_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_0_1, self.TXT_SKILL_0_0_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_0_2, self.TXT_SKILL_0_1_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_1_0, self.TXT_SKILL_0_1_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_1_1, self.TXT_SKILL_0_1_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_1_2, self.TXT_SKILL_0_2_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_2_0, self.TXT_SKILL_0_2_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_2_1, self.TXT_SKILL_0_2_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_0_2_2, self.TXT_SKILL_1_0_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_0_0, self.TXT_SKILL_1_0_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_0_1, self.TXT_SKILL_1_0_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_0_2, self.TXT_SKILL_1_1_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_1_0, self.TXT_SKILL_1_1_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_1_1, self.TXT_SKILL_1_1_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_1_2, self.TXT_SKILL_1_2_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_2_0, self.TXT_SKILL_1_2_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_2_1, self.TXT_SKILL_1_2_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_1_2_2, self.TXT_SKILL_2_0_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_0_0, self.TXT_SKILL_2_0_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_0_1, self.TXT_SKILL_2_0_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_0_2, self.TXT_SKILL_2_1_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_1_0, self.TXT_SKILL_2_1_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_1_1, self.TXT_SKILL_2_1_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_1_2, self.TXT_SKILL_2_2_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_2_0, self.TXT_SKILL_2_2_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_2_1, self.TXT_SKILL_2_2_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_2_2_2, self.TXT_SKILL_3_0_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_0_0, self.TXT_SKILL_3_0_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_0_1, self.TXT_SKILL_3_0_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_0_2, self.TXT_SKILL_3_1_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_1_0, self.TXT_SKILL_3_1_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_1_1, self.TXT_SKILL_3_1_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_1_2, self.TXT_SKILL_3_2_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_2_0, self.TXT_SKILL_3_2_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_2_1, self.TXT_SKILL_3_2_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_3_2_2, self.TXT_SKILL_4_0_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_0_0, self.TXT_SKILL_4_0_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_0_1, self.TXT_SKILL_4_0_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_0_2, self.TXT_SKILL_4_1_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_1_0, self.TXT_SKILL_4_1_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_1_1, self.TXT_SKILL_4_1_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_1_2, self.TXT_SKILL_4_2_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_2_0, self.TXT_SKILL_4_2_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_2_1, self.TXT_SKILL_4_2_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_4_2_2, self.TXT_SKILL_5_0_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_0_0, self.TXT_SKILL_5_0_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_0_1, self.TXT_SKILL_5_0_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_0_2, self.TXT_SKILL_5_1_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_1_0, self.TXT_SKILL_5_1_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_1_1, self.TXT_SKILL_5_1_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_1_2, self.TXT_SKILL_5_2_0)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_2_0, self.TXT_SKILL_5_2_1)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_2_1, self.TXT_SKILL_5_2_2)
        fgoMainWindow.setTabOrder(self.TXT_SKILL_5_2_2, self.TXT_HOUGU_0_0)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_0_0, self.TXT_HOUGU_0_1)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_0_1, self.TXT_HOUGU_1_0)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_1_0, self.TXT_HOUGU_1_1)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_1_1, self.TXT_HOUGU_2_0)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_2_0, self.TXT_HOUGU_2_1)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_2_1, self.TXT_HOUGU_3_0)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_3_0, self.TXT_HOUGU_3_1)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_3_1, self.TXT_HOUGU_4_0)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_4_0, self.TXT_HOUGU_4_1)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_4_1, self.TXT_HOUGU_5_0)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_5_0, self.TXT_HOUGU_5_1)
        fgoMainWindow.setTabOrder(self.TXT_HOUGU_5_1, self.TXT_DANGER_0)
        fgoMainWindow.setTabOrder(self.TXT_DANGER_0, self.TXT_DANGER_1)
        fgoMainWindow.setTabOrder(self.TXT_DANGER_1, self.TXT_DANGER_2)
        fgoMainWindow.setTabOrder(self.TXT_DANGER_2, self.CBX_APPLE)
        fgoMainWindow.setTabOrder(self.CBX_APPLE, self.TXT_APPLE)
        fgoMainWindow.setTabOrder(self.TXT_APPLE, self.BTN_GETHWND)
        fgoMainWindow.setTabOrder(self.BTN_GETHWND, self.BTN_CHECK)
        fgoMainWindow.setTabOrder(self.BTN_CHECK, self.BTN_DRAW)
        fgoMainWindow.setTabOrder(self.BTN_DRAW, self.BTN_ONEBATTLE)
        fgoMainWindow.setTabOrder(self.BTN_ONEBATTLE, self.BTN_MAIN)
        fgoMainWindow.setTabOrder(self.BTN_MAIN, self.BTN_PAUSE)
        fgoMainWindow.setTabOrder(self.BTN_PAUSE, self.BTN_STOP)

    def retranslateUi(self, fgoMainWindow):
        _translate = QtCore.QCoreApplication.translate
        fgoMainWindow.setWindowTitle(_translate("fgoMainWindow", "FGO script"))
        self.BTN_PARTYSAVE.setText(_translate("fgoMainWindow", "保存"))
        self.BTN_PARTYRESET.setText(_translate("fgoMainWindow", "重置"))
        self.LBL_SKILLINFO.setText(_translate("fgoMainWindow", "编队信息"))
        self.LBL_PARTY_0.setText(_translate("fgoMainWindow", "1"))
        self.TXT_SKILL_0_0_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_0_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_0_0_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_0_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_0_0_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_0_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_0_1_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_1_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_0_1_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_1_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_0_1_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_1_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_0_2_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_2_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_0_2_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_2_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_0_2_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_0_2_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_HOUGU_0_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_0_0.setText(_translate("fgoMainWindow", "1"))
        self.TXT_HOUGU_0_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_0_1.setText(_translate("fgoMainWindow", "1"))
        self.LBL_PARTY_1.setText(_translate("fgoMainWindow", "2"))
        self.TXT_SKILL_1_0_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_0_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_1_0_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_0_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_1_0_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_0_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_1_1_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_1_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_1_1_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_1_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_1_1_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_1_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_1_2_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_2_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_1_2_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_2_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_1_2_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_1_2_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_HOUGU_1_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_1_0.setText(_translate("fgoMainWindow", "1"))
        self.TXT_HOUGU_1_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_1_1.setText(_translate("fgoMainWindow", "1"))
        self.LBL_PARTY_2.setText(_translate("fgoMainWindow", "3"))
        self.TXT_SKILL_2_0_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_0_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_2_0_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_0_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_2_0_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_0_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_2_1_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_1_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_2_1_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_1_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_2_1_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_1_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_2_2_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_2_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_2_2_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_2_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_2_2_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_2_2_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_HOUGU_2_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_2_0.setText(_translate("fgoMainWindow", "1"))
        self.TXT_HOUGU_2_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_2_1.setText(_translate("fgoMainWindow", "1"))
        self.LBL_PARTY_3.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_3_0_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_0_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_3_0_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_0_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_3_0_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_0_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_3_1_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_1_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_3_1_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_1_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_3_1_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_1_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_3_2_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_2_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_3_2_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_2_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_3_2_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_3_2_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_HOUGU_3_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_3_0.setText(_translate("fgoMainWindow", "1"))
        self.TXT_HOUGU_3_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_3_1.setText(_translate("fgoMainWindow", "1"))
        self.LBL_PARTY_4.setText(_translate("fgoMainWindow", "5"))
        self.TXT_SKILL_4_0_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_0_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_4_0_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_0_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_4_0_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_0_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_4_1_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_1_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_4_1_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_1_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_4_1_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_1_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_4_2_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_2_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_4_2_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_2_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_4_2_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_4_2_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_HOUGU_4_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_4_0.setText(_translate("fgoMainWindow", "1"))
        self.TXT_HOUGU_4_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_4_1.setText(_translate("fgoMainWindow", "1"))
        self.LBL_PARTY_5.setText(_translate("fgoMainWindow", "6"))
        self.TXT_SKILL_5_0_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_0_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_5_0_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_0_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_5_0_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_0_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_5_1_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_1_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_5_1_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_1_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_5_1_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_1_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_5_2_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_2_0.setText(_translate("fgoMainWindow", "4"))
        self.TXT_SKILL_5_2_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_2_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_SKILL_5_2_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_SKILL_5_2_2.setText(_translate("fgoMainWindow", "0"))
        self.TXT_HOUGU_5_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_5_0.setText(_translate("fgoMainWindow", "1"))
        self.TXT_HOUGU_5_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_HOUGU_5_1.setText(_translate("fgoMainWindow", "1"))
        self.LBL_DANGERPOS.setText(_translate("fgoMainWindow", "优先攻击"))
        self.TXT_DANGER_0.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_DANGER_0.setText(_translate("fgoMainWindow", "0"))
        self.TXT_DANGER_1.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_DANGER_1.setText(_translate("fgoMainWindow", "0"))
        self.TXT_DANGER_2.setInputMask(_translate("fgoMainWindow", "9"))
        self.TXT_DANGER_2.setText(_translate("fgoMainWindow", "1"))
        self.LBL_APPLE.setText(_translate("fgoMainWindow", "苹果"))
        self.CBX_APPLE.setItemText(0, _translate("fgoMainWindow", "金"))
        self.CBX_APPLE.setItemText(1, _translate("fgoMainWindow", "银"))
        self.CBX_APPLE.setItemText(2, _translate("fgoMainWindow", "铜"))
        self.CBX_APPLE.setItemText(3, _translate("fgoMainWindow", "彩"))
        self.TXT_APPLE.setText(_translate("fgoMainWindow", "0"))
        self.BTN_GETDEVICE.setText(_translate("fgoMainWindow", "更改安卓设备"))
        self.BTN_ADBCONNECT.setText(_translate("fgoMainWindow", "连接远程设备"))
        self.BTN_GETHWND.setText(_translate("fgoMainWindow", "获取窗口句柄"))
        self.BTN_CHECK.setText(_translate("fgoMainWindow", "检查截图"))
        self.BTN_GETFRIEND.setText(_translate("fgoMainWindow", "刷新助战模板"))
        self.BTN_DRAW.setText(_translate("fgoMainWindow", "抽奖池"))
        self.BTN_ONEBATTLE.setText(_translate("fgoMainWindow", "完成战斗"))
        self.BTN_MAIN.setText(_translate("fgoMainWindow", "肝!"))
        self.BTN_PAUSE.setText(_translate("fgoMainWindow", "挂起战斗"))
        self.BTN_STOP.setText(_translate("fgoMainWindow", "终止战斗"))
        self.MENU_ABOUT.setTitle(_translate("fgoMainWindow", "About"))
        self.MENU_ABOUT_UNDEFINED.setText(_translate("fgoMainWindow", "我还没想好这里应该写点啥"))
