# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 529)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LAYOUT_PARTY = QtWidgets.QHBoxLayout()
        self.LAYOUT_PARTY.setObjectName("LAYOUT_PARTY")
        self.CBX_PARTY = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CBX_PARTY.sizePolicy().hasHeightForWidth())
        self.CBX_PARTY.setSizePolicy(sizePolicy)
        self.CBX_PARTY.setObjectName("CBX_PARTY")
        self.LAYOUT_PARTY.addWidget(self.CBX_PARTY)
        self.BTN_PARTYSAVE = QtWidgets.QPushButton(self.widget)
        self.BTN_PARTYSAVE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_PARTYSAVE.setObjectName("BTN_PARTYSAVE")
        self.LAYOUT_PARTY.addWidget(self.BTN_PARTYSAVE)
        self.BTN_PARTYRESET = QtWidgets.QPushButton(self.widget)
        self.BTN_PARTYRESET.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_PARTYRESET.setObjectName("BTN_PARTYRESET")
        self.LAYOUT_PARTY.addWidget(self.BTN_PARTYRESET)
        self.verticalLayout.addLayout(self.LAYOUT_PARTY)
        self.LAYOUT_INFO = QtWidgets.QFormLayout()
        self.LAYOUT_INFO.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LAYOUT_INFO.setObjectName("LAYOUT_INFO")
        self.LBL_SKILLINFO = QtWidgets.QLabel(self.widget)
        self.LBL_SKILLINFO.setObjectName("LBL_SKILLINFO")
        self.LAYOUT_INFO.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LBL_SKILLINFO)
        self.LAYOUT_INFO_PARTY = QtWidgets.QFormLayout()
        self.LAYOUT_INFO_PARTY.setObjectName("LAYOUT_INFO_PARTY")
        self.LBL_PARTY_0 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_0.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_0.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_0.setObjectName("LBL_PARTY_0")
        self.LAYOUT_INFO_PARTY.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_0)
        self.LAYOUT_INFO_PARTY_0 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_0.setObjectName("LAYOUT_INFO_PARTY_0")
        self.RBT_FRIEND_0 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_0.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_0.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_0.setText("")
        self.RBT_FRIEND_0.setObjectName("RBT_FRIEND_0")
        self.BTG_FRIEND = QtWidgets.QButtonGroup(MainWindow)
        self.BTG_FRIEND.setObjectName("BTG_FRIEND")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_0)
        self.LAYOUT_INFO_PARTY_0.addWidget(self.RBT_FRIEND_0)
        self.TXT_SKILL_0_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_0.setMaxLength(1)
        self.TXT_SKILL_0_0_0.setObjectName("TXT_SKILL_0_0_0")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_0_0)
        self.TXT_SKILL_0_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_1.setMaxLength(1)
        self.TXT_SKILL_0_0_1.setObjectName("TXT_SKILL_0_0_1")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_0_1)
        self.TXT_SKILL_0_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_2.setMaxLength(1)
        self.TXT_SKILL_0_0_2.setObjectName("TXT_SKILL_0_0_2")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_0_2)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_0.addItem(spacerItem)
        self.TXT_SKILL_0_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_0.setMaxLength(1)
        self.TXT_SKILL_0_1_0.setObjectName("TXT_SKILL_0_1_0")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_1_0)
        self.TXT_SKILL_0_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_1.setMaxLength(1)
        self.TXT_SKILL_0_1_1.setObjectName("TXT_SKILL_0_1_1")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_1_1)
        self.TXT_SKILL_0_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_2.setMaxLength(1)
        self.TXT_SKILL_0_1_2.setObjectName("TXT_SKILL_0_1_2")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_1_2)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_0.addItem(spacerItem1)
        self.TXT_SKILL_0_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_0.setMaxLength(1)
        self.TXT_SKILL_0_2_0.setObjectName("TXT_SKILL_0_2_0")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_2_0)
        self.TXT_SKILL_0_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_1.setMaxLength(1)
        self.TXT_SKILL_0_2_1.setObjectName("TXT_SKILL_0_2_1")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_2_1)
        self.TXT_SKILL_0_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_0_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_2.setMaxLength(1)
        self.TXT_SKILL_0_2_2.setObjectName("TXT_SKILL_0_2_2")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_SKILL_0_2_2)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_0.addItem(spacerItem2)
        self.TXT_HOUGU_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_0.setMaxLength(1)
        self.TXT_HOUGU_0_0.setObjectName("TXT_HOUGU_0_0")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_HOUGU_0_0)
        self.TXT_HOUGU_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_1.setMaxLength(1)
        self.TXT_HOUGU_0_1.setObjectName("TXT_HOUGU_0_1")
        self.LAYOUT_INFO_PARTY_0.addWidget(self.TXT_HOUGU_0_1)
        self.LAYOUT_INFO_PARTY.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_0)
        self.LBL_PARTY_1 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_1.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_1.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_1.setObjectName("LBL_PARTY_1")
        self.LAYOUT_INFO_PARTY.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_1)
        self.LAYOUT_INFO_PARTY_1 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_1.setObjectName("LAYOUT_INFO_PARTY_1")
        self.RBT_FRIEND_1 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_1.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_1.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_1.setText("")
        self.RBT_FRIEND_1.setObjectName("RBT_FRIEND_1")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_1)
        self.LAYOUT_INFO_PARTY_1.addWidget(self.RBT_FRIEND_1)
        self.TXT_SKILL_1_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_0.setMaxLength(1)
        self.TXT_SKILL_1_0_0.setObjectName("TXT_SKILL_1_0_0")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_0_0)
        self.TXT_SKILL_1_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_1.setMaxLength(1)
        self.TXT_SKILL_1_0_1.setObjectName("TXT_SKILL_1_0_1")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_0_1)
        self.TXT_SKILL_1_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_2.setMaxLength(1)
        self.TXT_SKILL_1_0_2.setObjectName("TXT_SKILL_1_0_2")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_0_2)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_1.addItem(spacerItem3)
        self.TXT_SKILL_1_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_0.setMaxLength(1)
        self.TXT_SKILL_1_1_0.setObjectName("TXT_SKILL_1_1_0")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_1_0)
        self.TXT_SKILL_1_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_1.setMaxLength(1)
        self.TXT_SKILL_1_1_1.setObjectName("TXT_SKILL_1_1_1")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_1_1)
        self.TXT_SKILL_1_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_2.setMaxLength(1)
        self.TXT_SKILL_1_1_2.setObjectName("TXT_SKILL_1_1_2")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_1_2)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_1.addItem(spacerItem4)
        self.TXT_SKILL_1_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_0.setMaxLength(1)
        self.TXT_SKILL_1_2_0.setObjectName("TXT_SKILL_1_2_0")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_2_0)
        self.TXT_SKILL_1_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_1.setMaxLength(1)
        self.TXT_SKILL_1_2_1.setObjectName("TXT_SKILL_1_2_1")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_2_1)
        self.TXT_SKILL_1_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_1_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_2.setMaxLength(1)
        self.TXT_SKILL_1_2_2.setObjectName("TXT_SKILL_1_2_2")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_SKILL_1_2_2)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_1.addItem(spacerItem5)
        self.TXT_HOUGU_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_0.setMaxLength(1)
        self.TXT_HOUGU_1_0.setObjectName("TXT_HOUGU_1_0")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_HOUGU_1_0)
        self.TXT_HOUGU_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_1.setMaxLength(1)
        self.TXT_HOUGU_1_1.setObjectName("TXT_HOUGU_1_1")
        self.LAYOUT_INFO_PARTY_1.addWidget(self.TXT_HOUGU_1_1)
        self.LAYOUT_INFO_PARTY.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_1)
        self.LBL_PARTY_2 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_2.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_2.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_2.setObjectName("LBL_PARTY_2")
        self.LAYOUT_INFO_PARTY.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_2)
        self.LAYOUT_INFO_PARTY_2 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_2.setObjectName("LAYOUT_INFO_PARTY_2")
        self.RBT_FRIEND_2 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_2.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_2.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_2.setText("")
        self.RBT_FRIEND_2.setObjectName("RBT_FRIEND_2")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_2)
        self.LAYOUT_INFO_PARTY_2.addWidget(self.RBT_FRIEND_2)
        self.TXT_SKILL_2_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_0.setMaxLength(1)
        self.TXT_SKILL_2_0_0.setObjectName("TXT_SKILL_2_0_0")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_0_0)
        self.TXT_SKILL_2_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_1.setMaxLength(1)
        self.TXT_SKILL_2_0_1.setObjectName("TXT_SKILL_2_0_1")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_0_1)
        self.TXT_SKILL_2_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_2.setMaxLength(1)
        self.TXT_SKILL_2_0_2.setObjectName("TXT_SKILL_2_0_2")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_0_2)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_2.addItem(spacerItem6)
        self.TXT_SKILL_2_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_0.setMaxLength(1)
        self.TXT_SKILL_2_1_0.setObjectName("TXT_SKILL_2_1_0")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_1_0)
        self.TXT_SKILL_2_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_1.setMaxLength(1)
        self.TXT_SKILL_2_1_1.setObjectName("TXT_SKILL_2_1_1")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_1_1)
        self.TXT_SKILL_2_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_2.setMaxLength(1)
        self.TXT_SKILL_2_1_2.setObjectName("TXT_SKILL_2_1_2")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_1_2)
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_2.addItem(spacerItem7)
        self.TXT_SKILL_2_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_0.setMaxLength(1)
        self.TXT_SKILL_2_2_0.setObjectName("TXT_SKILL_2_2_0")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_2_0)
        self.TXT_SKILL_2_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_1.setMaxLength(1)
        self.TXT_SKILL_2_2_1.setObjectName("TXT_SKILL_2_2_1")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_2_1)
        self.TXT_SKILL_2_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_2_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_2.setMaxLength(1)
        self.TXT_SKILL_2_2_2.setObjectName("TXT_SKILL_2_2_2")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_SKILL_2_2_2)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_2.addItem(spacerItem8)
        self.TXT_HOUGU_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_0.setMaxLength(1)
        self.TXT_HOUGU_2_0.setObjectName("TXT_HOUGU_2_0")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_HOUGU_2_0)
        self.TXT_HOUGU_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_1.setMaxLength(1)
        self.TXT_HOUGU_2_1.setObjectName("TXT_HOUGU_2_1")
        self.LAYOUT_INFO_PARTY_2.addWidget(self.TXT_HOUGU_2_1)
        self.LAYOUT_INFO_PARTY.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_2)
        self.LBL_PARTY_3 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_3.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_3.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_3.setObjectName("LBL_PARTY_3")
        self.LAYOUT_INFO_PARTY.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_3)
        self.LAYOUT_INFO_PARTY_3 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_3.setObjectName("LAYOUT_INFO_PARTY_3")
        self.RBT_FRIEND_3 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_3.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_3.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_3.setText("")
        self.RBT_FRIEND_3.setObjectName("RBT_FRIEND_3")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_3)
        self.LAYOUT_INFO_PARTY_3.addWidget(self.RBT_FRIEND_3)
        self.TXT_SKILL_3_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_0.setMaxLength(1)
        self.TXT_SKILL_3_0_0.setObjectName("TXT_SKILL_3_0_0")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_0_0)
        self.TXT_SKILL_3_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_1.setMaxLength(1)
        self.TXT_SKILL_3_0_1.setObjectName("TXT_SKILL_3_0_1")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_0_1)
        self.TXT_SKILL_3_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_2.setMaxLength(1)
        self.TXT_SKILL_3_0_2.setObjectName("TXT_SKILL_3_0_2")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_0_2)
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_3.addItem(spacerItem9)
        self.TXT_SKILL_3_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_0.setMaxLength(1)
        self.TXT_SKILL_3_1_0.setObjectName("TXT_SKILL_3_1_0")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_1_0)
        self.TXT_SKILL_3_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_1.setMaxLength(1)
        self.TXT_SKILL_3_1_1.setObjectName("TXT_SKILL_3_1_1")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_1_1)
        self.TXT_SKILL_3_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_2.setMaxLength(1)
        self.TXT_SKILL_3_1_2.setObjectName("TXT_SKILL_3_1_2")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_1_2)
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_3.addItem(spacerItem10)
        self.TXT_SKILL_3_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_0.setMaxLength(1)
        self.TXT_SKILL_3_2_0.setObjectName("TXT_SKILL_3_2_0")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_2_0)
        self.TXT_SKILL_3_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_1.setMaxLength(1)
        self.TXT_SKILL_3_2_1.setObjectName("TXT_SKILL_3_2_1")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_2_1)
        self.TXT_SKILL_3_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_3_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_2.setMaxLength(1)
        self.TXT_SKILL_3_2_2.setObjectName("TXT_SKILL_3_2_2")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_SKILL_3_2_2)
        spacerItem11 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_3.addItem(spacerItem11)
        self.TXT_HOUGU_3_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_3_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_0.setMaxLength(1)
        self.TXT_HOUGU_3_0.setObjectName("TXT_HOUGU_3_0")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_HOUGU_3_0)
        self.TXT_HOUGU_3_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_3_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_1.setMaxLength(1)
        self.TXT_HOUGU_3_1.setObjectName("TXT_HOUGU_3_1")
        self.LAYOUT_INFO_PARTY_3.addWidget(self.TXT_HOUGU_3_1)
        self.LAYOUT_INFO_PARTY.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_3)
        self.LBL_PARTY_4 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_4.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_4.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_4.setObjectName("LBL_PARTY_4")
        self.LAYOUT_INFO_PARTY.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_4)
        self.LAYOUT_INFO_PARTY_4 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_4.setObjectName("LAYOUT_INFO_PARTY_4")
        self.RBT_FRIEND_4 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_4.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_4.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBT_FRIEND_4.setText("")
        self.RBT_FRIEND_4.setChecked(True)
        self.RBT_FRIEND_4.setObjectName("RBT_FRIEND_4")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_4)
        self.LAYOUT_INFO_PARTY_4.addWidget(self.RBT_FRIEND_4)
        self.TXT_SKILL_4_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_0.setMaxLength(1)
        self.TXT_SKILL_4_0_0.setObjectName("TXT_SKILL_4_0_0")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_0_0)
        self.TXT_SKILL_4_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_1.setMaxLength(1)
        self.TXT_SKILL_4_0_1.setObjectName("TXT_SKILL_4_0_1")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_0_1)
        self.TXT_SKILL_4_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_2.setMaxLength(1)
        self.TXT_SKILL_4_0_2.setObjectName("TXT_SKILL_4_0_2")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_0_2)
        spacerItem12 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_4.addItem(spacerItem12)
        self.TXT_SKILL_4_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_0.setMaxLength(1)
        self.TXT_SKILL_4_1_0.setObjectName("TXT_SKILL_4_1_0")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_1_0)
        self.TXT_SKILL_4_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_1.setMaxLength(1)
        self.TXT_SKILL_4_1_1.setObjectName("TXT_SKILL_4_1_1")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_1_1)
        self.TXT_SKILL_4_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_2.setMaxLength(1)
        self.TXT_SKILL_4_1_2.setObjectName("TXT_SKILL_4_1_2")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_1_2)
        spacerItem13 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_4.addItem(spacerItem13)
        self.TXT_SKILL_4_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_0.setMaxLength(1)
        self.TXT_SKILL_4_2_0.setObjectName("TXT_SKILL_4_2_0")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_2_0)
        self.TXT_SKILL_4_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_1.setMaxLength(1)
        self.TXT_SKILL_4_2_1.setObjectName("TXT_SKILL_4_2_1")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_2_1)
        self.TXT_SKILL_4_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_4_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_2.setMaxLength(1)
        self.TXT_SKILL_4_2_2.setObjectName("TXT_SKILL_4_2_2")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_SKILL_4_2_2)
        spacerItem14 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_4.addItem(spacerItem14)
        self.TXT_HOUGU_4_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_4_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_0.setMaxLength(1)
        self.TXT_HOUGU_4_0.setObjectName("TXT_HOUGU_4_0")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_HOUGU_4_0)
        self.TXT_HOUGU_4_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_4_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_1.setMaxLength(1)
        self.TXT_HOUGU_4_1.setObjectName("TXT_HOUGU_4_1")
        self.LAYOUT_INFO_PARTY_4.addWidget(self.TXT_HOUGU_4_1)
        self.LAYOUT_INFO_PARTY.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_4)
        self.LBL_PARTY_5 = QtWidgets.QLabel(self.widget)
        self.LBL_PARTY_5.setMinimumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_5.setMaximumSize(QtCore.QSize(12, 24))
        self.LBL_PARTY_5.setObjectName("LBL_PARTY_5")
        self.LAYOUT_INFO_PARTY.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.LBL_PARTY_5)
        self.LAYOUT_INFO_PARTY_5 = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_PARTY_5.setObjectName("LAYOUT_INFO_PARTY_5")
        self.RBT_FRIEND_5 = QtWidgets.QRadioButton(self.widget)
        self.RBT_FRIEND_5.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_5.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_FRIEND_5.setText("")
        self.RBT_FRIEND_5.setChecked(False)
        self.RBT_FRIEND_5.setObjectName("RBT_FRIEND_5")
        self.BTG_FRIEND.addButton(self.RBT_FRIEND_5)
        self.LAYOUT_INFO_PARTY_5.addWidget(self.RBT_FRIEND_5)
        self.TXT_SKILL_5_0_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_0.setMaxLength(1)
        self.TXT_SKILL_5_0_0.setObjectName("TXT_SKILL_5_0_0")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_0_0)
        self.TXT_SKILL_5_0_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_1.setMaxLength(1)
        self.TXT_SKILL_5_0_1.setObjectName("TXT_SKILL_5_0_1")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_0_1)
        self.TXT_SKILL_5_0_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_2.setMaxLength(1)
        self.TXT_SKILL_5_0_2.setObjectName("TXT_SKILL_5_0_2")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_0_2)
        spacerItem15 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_5.addItem(spacerItem15)
        self.TXT_SKILL_5_1_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_0.setMaxLength(1)
        self.TXT_SKILL_5_1_0.setObjectName("TXT_SKILL_5_1_0")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_1_0)
        self.TXT_SKILL_5_1_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_1.setMaxLength(1)
        self.TXT_SKILL_5_1_1.setObjectName("TXT_SKILL_5_1_1")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_1_1)
        self.TXT_SKILL_5_1_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_2.setMaxLength(1)
        self.TXT_SKILL_5_1_2.setObjectName("TXT_SKILL_5_1_2")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_1_2)
        spacerItem16 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_5.addItem(spacerItem16)
        self.TXT_SKILL_5_2_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_0.setMaxLength(1)
        self.TXT_SKILL_5_2_0.setObjectName("TXT_SKILL_5_2_0")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_2_0)
        self.TXT_SKILL_5_2_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_1.setMaxLength(1)
        self.TXT_SKILL_5_2_1.setObjectName("TXT_SKILL_5_2_1")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_2_1)
        self.TXT_SKILL_5_2_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_SKILL_5_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_2.setMaxLength(1)
        self.TXT_SKILL_5_2_2.setObjectName("TXT_SKILL_5_2_2")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_SKILL_5_2_2)
        spacerItem17 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_PARTY_5.addItem(spacerItem17)
        self.TXT_HOUGU_5_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_5_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_0.setMaxLength(1)
        self.TXT_HOUGU_5_0.setObjectName("TXT_HOUGU_5_0")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_HOUGU_5_0)
        self.TXT_HOUGU_5_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_HOUGU_5_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_1.setMaxLength(1)
        self.TXT_HOUGU_5_1.setObjectName("TXT_HOUGU_5_1")
        self.LAYOUT_INFO_PARTY_5.addWidget(self.TXT_HOUGU_5_1)
        self.LAYOUT_INFO_PARTY.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY_5)
        self.LAYOUT_INFO.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_PARTY)
        self.LBL_DANGERPOS = QtWidgets.QLabel(self.widget)
        self.LBL_DANGERPOS.setObjectName("LBL_DANGERPOS")
        self.LAYOUT_INFO.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LBL_DANGERPOS)
        self.LAYOUT_INFO_DANGER = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_DANGER.setObjectName("LAYOUT_INFO_DANGER")
        self.TXT_DANGER_0 = QtWidgets.QLineEdit(self.widget)
        self.TXT_DANGER_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_0.setMaxLength(1)
        self.TXT_DANGER_0.setObjectName("TXT_DANGER_0")
        self.LAYOUT_INFO_DANGER.addWidget(self.TXT_DANGER_0)
        spacerItem18 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_DANGER.addItem(spacerItem18)
        self.TXT_DANGER_1 = QtWidgets.QLineEdit(self.widget)
        self.TXT_DANGER_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_1.setMaxLength(1)
        self.TXT_DANGER_1.setObjectName("TXT_DANGER_1")
        self.LAYOUT_INFO_DANGER.addWidget(self.TXT_DANGER_1)
        spacerItem19 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LAYOUT_INFO_DANGER.addItem(spacerItem19)
        self.TXT_DANGER_2 = QtWidgets.QLineEdit(self.widget)
        self.TXT_DANGER_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_2.setMaxLength(1)
        self.TXT_DANGER_2.setObjectName("TXT_DANGER_2")
        self.LAYOUT_INFO_DANGER.addWidget(self.TXT_DANGER_2)
        self.LAYOUT_INFO.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_DANGER)
        self.LBL_APPLE = QtWidgets.QLabel(self.widget)
        self.LBL_APPLE.setObjectName("LBL_APPLE")
        self.LAYOUT_INFO.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LBL_APPLE)
        self.LAYOUT_INFO_APPLE = QtWidgets.QHBoxLayout()
        self.LAYOUT_INFO_APPLE.setObjectName("LAYOUT_INFO_APPLE")
        self.CBX_APPLE = QtWidgets.QComboBox(self.widget)
        self.CBX_APPLE.setObjectName("CBX_APPLE")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.LAYOUT_INFO_APPLE.addWidget(self.CBX_APPLE)
        self.TXT_APPLE = QtWidgets.QLineEdit(self.widget)
        self.TXT_APPLE.setMaxLength(10)
        self.TXT_APPLE.setObjectName("TXT_APPLE")
        self.LAYOUT_INFO_APPLE.addWidget(self.TXT_APPLE)
        self.LAYOUT_INFO.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.LAYOUT_INFO_APPLE)
        self.verticalLayout.addLayout(self.LAYOUT_INFO)
        self.LAYOUT_ADBCONNECT = QtWidgets.QHBoxLayout()
        self.LAYOUT_ADBCONNECT.setObjectName("LAYOUT_ADBCONNECT")
        self.TXT_ADDRESS = QtWidgets.QLineEdit(self.widget)
        self.TXT_ADDRESS.setMaxLength(50)
        self.TXT_ADDRESS.setObjectName("TXT_ADDRESS")
        self.LAYOUT_ADBCONNECT.addWidget(self.TXT_ADDRESS)
        self.BTN_CONNECT = QtWidgets.QPushButton(self.widget)
        self.BTN_CONNECT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_CONNECT.setCheckable(False)
        self.BTN_CONNECT.setChecked(False)
        self.BTN_CONNECT.setObjectName("BTN_CONNECT")
        self.LAYOUT_ADBCONNECT.addWidget(self.BTN_CONNECT)
        self.BTN_DISCONNECT = QtWidgets.QPushButton(self.widget)
        self.BTN_DISCONNECT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_DISCONNECT.setObjectName("BTN_DISCONNECT")
        self.LAYOUT_ADBCONNECT.addWidget(self.BTN_DISCONNECT)
        self.verticalLayout.addLayout(self.LAYOUT_ADBCONNECT)
        self.LAYOUT_DEVICE = QtWidgets.QHBoxLayout()
        self.LAYOUT_DEVICE.setObjectName("LAYOUT_DEVICE")
        self.BTN_GETDEVICE = QtWidgets.QPushButton(self.widget)
        self.BTN_GETDEVICE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_GETDEVICE.setObjectName("BTN_GETDEVICE")
        self.LAYOUT_DEVICE.addWidget(self.BTN_GETDEVICE)
        self.CBX_DEVICE = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CBX_DEVICE.sizePolicy().hasHeightForWidth())
        self.CBX_DEVICE.setSizePolicy(sizePolicy)
        self.CBX_DEVICE.setEditable(True)
        self.CBX_DEVICE.setObjectName("CBX_DEVICE")
        self.LAYOUT_DEVICE.addWidget(self.CBX_DEVICE)
        self.BTN_TESTDEVICE = QtWidgets.QPushButton(self.widget)
        self.BTN_TESTDEVICE.setEnabled(False)
        self.BTN_TESTDEVICE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_TESTDEVICE.setObjectName("BTN_TESTDEVICE")
        self.LAYOUT_DEVICE.addWidget(self.BTN_TESTDEVICE)
        self.verticalLayout.addLayout(self.LAYOUT_DEVICE)
        self.LAYOUT_FUNC = QtWidgets.QHBoxLayout()
        self.LAYOUT_FUNC.setObjectName("LAYOUT_FUNC")
        self.LAYOUT_FUNC_WIN = QtWidgets.QVBoxLayout()
        self.LAYOUT_FUNC_WIN.setObjectName("LAYOUT_FUNC_WIN")
        self.BTN_GETHWND = QtWidgets.QPushButton(self.widget)
        self.BTN_GETHWND.setEnabled(True)
        self.BTN_GETHWND.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_GETHWND.setObjectName("BTN_GETHWND")
        self.LAYOUT_FUNC_WIN.addWidget(self.BTN_GETHWND)
        self.BTN_CHECK = QtWidgets.QPushButton(self.widget)
        self.BTN_CHECK.setEnabled(True)
        self.BTN_CHECK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_CHECK.setObjectName("BTN_CHECK")
        self.LAYOUT_FUNC_WIN.addWidget(self.BTN_CHECK)
        self.LAYOUT_FUNC.addLayout(self.LAYOUT_FUNC_WIN)
        self.LAYOUT_FUNC_MAIN = QtWidgets.QVBoxLayout()
        self.LAYOUT_FUNC_MAIN.setObjectName("LAYOUT_FUNC_MAIN")
        self.BTN_DRAW = QtWidgets.QPushButton(self.widget)
        self.BTN_DRAW.setEnabled(False)
        self.BTN_DRAW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_DRAW.setObjectName("BTN_DRAW")
        self.LAYOUT_FUNC_MAIN.addWidget(self.BTN_DRAW)
        self.BTN_ONEBATTLE = QtWidgets.QPushButton(self.widget)
        self.BTN_ONEBATTLE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_ONEBATTLE.setObjectName("BTN_ONEBATTLE")
        self.LAYOUT_FUNC_MAIN.addWidget(self.BTN_ONEBATTLE)
        self.BTN_MAIN = QtWidgets.QPushButton(self.widget)
        self.BTN_MAIN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_MAIN.setObjectName("BTN_MAIN")
        self.LAYOUT_FUNC_MAIN.addWidget(self.BTN_MAIN)
        self.LAYOUT_FUNC.addLayout(self.LAYOUT_FUNC_MAIN)
        self.LAYOUT_FUNC_CONTROL = QtWidgets.QVBoxLayout()
        self.LAYOUT_FUNC_CONTROL.setObjectName("LAYOUT_FUNC_CONTROL")
        self.BTN_PAUSE = QtWidgets.QPushButton(self.widget)
        self.BTN_PAUSE.setEnabled(False)
        self.BTN_PAUSE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_PAUSE.setObjectName("BTN_PAUSE")
        self.LAYOUT_FUNC_CONTROL.addWidget(self.BTN_PAUSE)
        self.BTN_STOP = QtWidgets.QPushButton(self.widget)
        self.BTN_STOP.setEnabled(False)
        self.BTN_STOP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_STOP.setObjectName("BTN_STOP")
        self.LAYOUT_FUNC_CONTROL.addWidget(self.BTN_STOP)
        self.LAYOUT_FUNC.addLayout(self.LAYOUT_FUNC_CONTROL)
        self.verticalLayout.addLayout(self.LAYOUT_FUNC)
        MainWindow.setCentralWidget(self.widget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menuBar.setObjectName("menuBar")
        self.MENU_ABOUT = QtWidgets.QMenu(self.menuBar)
        self.MENU_ABOUT.setObjectName("MENU_ABOUT")
        MainWindow.setMenuBar(self.menuBar)
        self.MENU_ABOUT_UNDEFINED = QtWidgets.QAction(MainWindow)
        self.MENU_ABOUT_UNDEFINED.setObjectName("MENU_ABOUT_UNDEFINED")
        self.MENU_ABOUT.addAction(self.MENU_ABOUT_UNDEFINED)
        self.menuBar.addAction(self.MENU_ABOUT.menuAction())

        self.retranslateUi(MainWindow)
        self.CBX_APPLE.setCurrentIndex(0)
        self.BTN_ONEBATTLE.clicked.connect(MainWindow.runOneBattle)
        self.BTN_MAIN.clicked.connect(MainWindow.runMain)
        self.BTN_CHECK.clicked.connect(MainWindow.checkCheck)
        self.BTN_GETHWND.clicked.connect(MainWindow.getHwnd)
        self.BTN_CONNECT.clicked.connect(MainWindow.adbConnect)
        self.BTN_GETDEVICE.clicked.connect(MainWindow.getDevice)
        self.BTN_DISCONNECT.clicked.connect(MainWindow.adbDisconnect)
        self.BTN_PAUSE.clicked.connect(MainWindow.pause)
        self.BTN_STOP.clicked.connect(MainWindow.stop)
        self.CBX_PARTY.activated['QString'].connect(MainWindow.loadParty)
        self.BTN_PARTYSAVE.clicked.connect(MainWindow.saveParty)
        self.BTN_PARTYRESET.clicked.connect(MainWindow.resetParty)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.CBX_PARTY, self.BTN_PARTYSAVE)
        MainWindow.setTabOrder(self.BTN_PARTYSAVE, self.BTN_PARTYRESET)
        MainWindow.setTabOrder(self.BTN_PARTYRESET, self.RBT_FRIEND_0)
        MainWindow.setTabOrder(self.RBT_FRIEND_0, self.RBT_FRIEND_1)
        MainWindow.setTabOrder(self.RBT_FRIEND_1, self.RBT_FRIEND_2)
        MainWindow.setTabOrder(self.RBT_FRIEND_2, self.RBT_FRIEND_3)
        MainWindow.setTabOrder(self.RBT_FRIEND_3, self.RBT_FRIEND_4)
        MainWindow.setTabOrder(self.RBT_FRIEND_4, self.RBT_FRIEND_5)
        MainWindow.setTabOrder(self.RBT_FRIEND_5, self.TXT_SKILL_0_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_0_0_0, self.TXT_SKILL_0_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_0_0_1, self.TXT_SKILL_0_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_0_0_2, self.TXT_SKILL_0_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_0_1_0, self.TXT_SKILL_0_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_0_1_1, self.TXT_SKILL_0_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_0_1_2, self.TXT_SKILL_0_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_0_2_0, self.TXT_SKILL_0_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_0_2_1, self.TXT_SKILL_0_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_0_2_2, self.TXT_SKILL_1_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_1_0_0, self.TXT_SKILL_1_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_1_0_1, self.TXT_SKILL_1_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_1_0_2, self.TXT_SKILL_1_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_1_1_0, self.TXT_SKILL_1_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_1_1_1, self.TXT_SKILL_1_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_1_1_2, self.TXT_SKILL_1_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_1_2_0, self.TXT_SKILL_1_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_1_2_1, self.TXT_SKILL_1_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_1_2_2, self.TXT_SKILL_2_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_2_0_0, self.TXT_SKILL_2_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_2_0_1, self.TXT_SKILL_2_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_2_0_2, self.TXT_SKILL_2_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_2_1_0, self.TXT_SKILL_2_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_2_1_1, self.TXT_SKILL_2_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_2_1_2, self.TXT_SKILL_2_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_2_2_0, self.TXT_SKILL_2_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_2_2_1, self.TXT_SKILL_2_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_2_2_2, self.TXT_SKILL_3_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_3_0_0, self.TXT_SKILL_3_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_3_0_1, self.TXT_SKILL_3_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_3_0_2, self.TXT_SKILL_3_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_3_1_0, self.TXT_SKILL_3_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_3_1_1, self.TXT_SKILL_3_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_3_1_2, self.TXT_SKILL_3_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_3_2_0, self.TXT_SKILL_3_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_3_2_1, self.TXT_SKILL_3_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_3_2_2, self.TXT_SKILL_4_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_4_0_0, self.TXT_SKILL_4_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_4_0_1, self.TXT_SKILL_4_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_4_0_2, self.TXT_SKILL_4_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_4_1_0, self.TXT_SKILL_4_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_4_1_1, self.TXT_SKILL_4_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_4_1_2, self.TXT_SKILL_4_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_4_2_0, self.TXT_SKILL_4_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_4_2_1, self.TXT_SKILL_4_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_4_2_2, self.TXT_SKILL_5_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_5_0_0, self.TXT_SKILL_5_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_5_0_1, self.TXT_SKILL_5_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_5_0_2, self.TXT_SKILL_5_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_5_1_0, self.TXT_SKILL_5_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_5_1_1, self.TXT_SKILL_5_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_5_1_2, self.TXT_SKILL_5_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_5_2_0, self.TXT_SKILL_5_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_5_2_1, self.TXT_SKILL_5_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_5_2_2, self.TXT_HOUGU_0_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_0_0, self.TXT_HOUGU_0_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_0_1, self.TXT_HOUGU_1_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_1_0, self.TXT_HOUGU_1_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_1_1, self.TXT_HOUGU_2_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_2_0, self.TXT_HOUGU_2_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_2_1, self.TXT_HOUGU_3_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_3_0, self.TXT_HOUGU_3_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_3_1, self.TXT_HOUGU_4_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_4_0, self.TXT_HOUGU_4_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_4_1, self.TXT_HOUGU_5_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_5_0, self.TXT_HOUGU_5_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_5_1, self.TXT_DANGER_0)
        MainWindow.setTabOrder(self.TXT_DANGER_0, self.TXT_DANGER_1)
        MainWindow.setTabOrder(self.TXT_DANGER_1, self.TXT_DANGER_2)
        MainWindow.setTabOrder(self.TXT_DANGER_2, self.CBX_APPLE)
        MainWindow.setTabOrder(self.CBX_APPLE, self.TXT_APPLE)
        MainWindow.setTabOrder(self.TXT_APPLE, self.TXT_ADDRESS)
        MainWindow.setTabOrder(self.TXT_ADDRESS, self.BTN_CONNECT)
        MainWindow.setTabOrder(self.BTN_CONNECT, self.BTN_DISCONNECT)
        MainWindow.setTabOrder(self.BTN_DISCONNECT, self.BTN_GETDEVICE)
        MainWindow.setTabOrder(self.BTN_GETDEVICE, self.CBX_DEVICE)
        MainWindow.setTabOrder(self.CBX_DEVICE, self.BTN_TESTDEVICE)
        MainWindow.setTabOrder(self.BTN_TESTDEVICE, self.BTN_DRAW)
        MainWindow.setTabOrder(self.BTN_DRAW, self.BTN_ONEBATTLE)
        MainWindow.setTabOrder(self.BTN_ONEBATTLE, self.BTN_MAIN)
        MainWindow.setTabOrder(self.BTN_MAIN, self.BTN_GETHWND)
        MainWindow.setTabOrder(self.BTN_GETHWND, self.BTN_CHECK)
        MainWindow.setTabOrder(self.BTN_CHECK, self.BTN_PAUSE)
        MainWindow.setTabOrder(self.BTN_PAUSE, self.BTN_STOP)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FGO script"))
        self.BTN_PARTYSAVE.setText(_translate("MainWindow", "保存"))
        self.BTN_PARTYRESET.setText(_translate("MainWindow", "重置"))
        self.LBL_SKILLINFO.setText(_translate("MainWindow", "编队信息"))
        self.LBL_PARTY_0.setText(_translate("MainWindow", "1"))
        self.TXT_SKILL_0_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_0_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_0_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_0_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_0_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_0_1.setText(_translate("MainWindow", "1"))
        self.LBL_PARTY_1.setText(_translate("MainWindow", "2"))
        self.TXT_SKILL_1_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_1_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_1_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_1_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_1_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_1_1.setText(_translate("MainWindow", "1"))
        self.LBL_PARTY_2.setText(_translate("MainWindow", "3"))
        self.TXT_SKILL_2_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_2_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_2_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_2_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_2_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_2_1.setText(_translate("MainWindow", "1"))
        self.LBL_PARTY_3.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_3_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_3_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_3_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_3_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_3_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_3_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_3_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_3_1.setText(_translate("MainWindow", "1"))
        self.LBL_PARTY_4.setText(_translate("MainWindow", "5"))
        self.TXT_SKILL_4_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_4_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_4_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_4_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_4_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_4_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_4_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_4_1.setText(_translate("MainWindow", "1"))
        self.LBL_PARTY_5.setText(_translate("MainWindow", "6"))
        self.TXT_SKILL_5_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_5_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_5_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_5_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_5_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_5_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_5_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_5_1.setText(_translate("MainWindow", "1"))
        self.LBL_DANGERPOS.setText(_translate("MainWindow", "优先攻击"))
        self.TXT_DANGER_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_DANGER_0.setText(_translate("MainWindow", "0"))
        self.TXT_DANGER_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_DANGER_1.setText(_translate("MainWindow", "0"))
        self.TXT_DANGER_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_DANGER_2.setText(_translate("MainWindow", "1"))
        self.LBL_APPLE.setText(_translate("MainWindow", "苹果"))
        self.CBX_APPLE.setItemText(0, _translate("MainWindow", "金"))
        self.CBX_APPLE.setItemText(1, _translate("MainWindow", "银"))
        self.CBX_APPLE.setItemText(2, _translate("MainWindow", "铜"))
        self.CBX_APPLE.setItemText(3, _translate("MainWindow", "彩"))
        self.TXT_APPLE.setText(_translate("MainWindow", "0"))
        self.TXT_ADDRESS.setText(_translate("MainWindow", "localhost:5555"))
        self.BTN_CONNECT.setText(_translate("MainWindow", "连接"))
        self.BTN_DISCONNECT.setText(_translate("MainWindow", "断开"))
        self.BTN_GETDEVICE.setText(_translate("MainWindow", "刷新"))
        self.BTN_TESTDEVICE.setText(_translate("MainWindow", "测试"))
        self.BTN_GETHWND.setText(_translate("MainWindow", "获取窗口句柄"))
        self.BTN_CHECK.setText(_translate("MainWindow", "检查截图"))
        self.BTN_DRAW.setText(_translate("MainWindow", "抽奖池"))
        self.BTN_ONEBATTLE.setText(_translate("MainWindow", "完成战斗"))
        self.BTN_MAIN.setText(_translate("MainWindow", "肝!"))
        self.BTN_PAUSE.setText(_translate("MainWindow", "挂起战斗"))
        self.BTN_STOP.setText(_translate("MainWindow", "终止战斗"))
        self.MENU_ABOUT.setTitle(_translate("MainWindow", "About"))
        self.MENU_ABOUT_UNDEFINED.setText(_translate("MainWindow", "我还没想好这里应该写点啥"))
