# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CBX_PARTY = QtWidgets.QComboBox(self.centralwidget)
        self.CBX_PARTY.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CBX_PARTY.sizePolicy().hasHeightForWidth())
        self.CBX_PARTY.setSizePolicy(sizePolicy)
        self.CBX_PARTY.setObjectName("CBX_PARTY")
        self.horizontalLayout.addWidget(self.CBX_PARTY)
        self.BTN_PARTYSAVE = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_PARTYSAVE.sizePolicy().hasHeightForWidth())
        self.BTN_PARTYSAVE.setSizePolicy(sizePolicy)
        self.BTN_PARTYSAVE.setMaximumSize(QtCore.QSize(48, 16777215))
        self.BTN_PARTYSAVE.setObjectName("BTN_PARTYSAVE")
        self.horizontalLayout.addWidget(self.BTN_PARTYSAVE)
        self.BTN_PARTYRESET = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_PARTYRESET.sizePolicy().hasHeightForWidth())
        self.BTN_PARTYRESET.setSizePolicy(sizePolicy)
        self.BTN_PARTYRESET.setMaximumSize(QtCore.QSize(48, 16777215))
        self.BTN_PARTYRESET.setObjectName("BTN_PARTYRESET")
        self.horizontalLayout.addWidget(self.BTN_PARTYRESET)
        self.BTN_PARTYDELETE = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_PARTYDELETE.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_PARTYDELETE.sizePolicy().hasHeightForWidth())
        self.BTN_PARTYDELETE.setSizePolicy(sizePolicy)
        self.BTN_PARTYDELETE.setMaximumSize(QtCore.QSize(48, 16777215))
        self.BTN_PARTYDELETE.setObjectName("BTN_PARTYDELETE")
        self.horizontalLayout.addWidget(self.BTN_PARTYDELETE)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.LBL_SKILLINFO = QtWidgets.QLabel(self.centralwidget)
        self.LBL_SKILLINFO.setObjectName("LBL_SKILLINFO")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LBL_SKILLINFO)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(12, 24))
        self.label_2.setMaximumSize(QtCore.QSize(12, 24))
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RBT_0 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBT_0.sizePolicy().hasHeightForWidth())
        self.RBT_0.setSizePolicy(sizePolicy)
        self.RBT_0.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_0.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_0.setText("")
        self.RBT_0.setObjectName("RBT_0")
        self.BTG_FRIEND = QtWidgets.QButtonGroup(MainWindow)
        self.BTG_FRIEND.setObjectName("BTG_FRIEND")
        self.BTG_FRIEND.addButton(self.RBT_0)
        self.horizontalLayout_4.addWidget(self.RBT_0)
        self.TXT_SKILL_0_0_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_0_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_0_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_0.setMaxLength(1)
        self.TXT_SKILL_0_0_0.setObjectName("TXT_SKILL_0_0_0")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_0_0)
        self.TXT_SKILL_0_0_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_0_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_0_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_1.setMaxLength(1)
        self.TXT_SKILL_0_0_1.setObjectName("TXT_SKILL_0_0_1")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_0_1)
        self.TXT_SKILL_0_0_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_0_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_0_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_0_2.setMaxLength(1)
        self.TXT_SKILL_0_0_2.setObjectName("TXT_SKILL_0_0_2")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_0_2)
        spacerItem = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.TXT_SKILL_0_1_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_1_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_1_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_0.setMaxLength(1)
        self.TXT_SKILL_0_1_0.setObjectName("TXT_SKILL_0_1_0")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_1_0)
        self.TXT_SKILL_0_1_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_1_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_1_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_1.setMaxLength(1)
        self.TXT_SKILL_0_1_1.setObjectName("TXT_SKILL_0_1_1")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_1_1)
        self.TXT_SKILL_0_1_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_1_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_1_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_1_2.setMaxLength(1)
        self.TXT_SKILL_0_1_2.setObjectName("TXT_SKILL_0_1_2")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_1_2)
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.TXT_SKILL_0_2_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_2_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_2_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_0.setMaxLength(1)
        self.TXT_SKILL_0_2_0.setObjectName("TXT_SKILL_0_2_0")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_2_0)
        self.TXT_SKILL_0_2_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_2_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_2_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_1.setMaxLength(1)
        self.TXT_SKILL_0_2_1.setObjectName("TXT_SKILL_0_2_1")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_2_1)
        self.TXT_SKILL_0_2_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_0_2_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_0_2_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_0_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_0_2_2.setMaxLength(1)
        self.TXT_SKILL_0_2_2.setObjectName("TXT_SKILL_0_2_2")
        self.horizontalLayout_4.addWidget(self.TXT_SKILL_0_2_2)
        spacerItem2 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.TXT_HOUGU_0_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_0_0.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_0_0.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_0.setMaxLength(1)
        self.TXT_HOUGU_0_0.setObjectName("TXT_HOUGU_0_0")
        self.horizontalLayout_4.addWidget(self.TXT_HOUGU_0_0)
        self.TXT_HOUGU_0_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_0_1.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_0_1.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_0_1.setMaxLength(1)
        self.TXT_HOUGU_0_1.setObjectName("TXT_HOUGU_0_1")
        self.horizontalLayout_4.addWidget(self.TXT_HOUGU_0_1)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(12, 24))
        self.label_3.setMaximumSize(QtCore.QSize(12, 24))
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.RBT_1 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBT_1.sizePolicy().hasHeightForWidth())
        self.RBT_1.setSizePolicy(sizePolicy)
        self.RBT_1.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_1.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_1.setText("")
        self.RBT_1.setObjectName("RBT_1")
        self.BTG_FRIEND.addButton(self.RBT_1)
        self.horizontalLayout_7.addWidget(self.RBT_1)
        self.TXT_SKILL_1_0_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_0_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_0_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_0.setMaxLength(1)
        self.TXT_SKILL_1_0_0.setObjectName("TXT_SKILL_1_0_0")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_0_0)
        self.TXT_SKILL_1_0_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_0_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_0_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_1.setMaxLength(1)
        self.TXT_SKILL_1_0_1.setObjectName("TXT_SKILL_1_0_1")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_0_1)
        self.TXT_SKILL_1_0_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_0_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_0_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_0_2.setMaxLength(1)
        self.TXT_SKILL_1_0_2.setObjectName("TXT_SKILL_1_0_2")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_0_2)
        spacerItem3 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.TXT_SKILL_1_1_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_1_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_1_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_0.setMaxLength(1)
        self.TXT_SKILL_1_1_0.setObjectName("TXT_SKILL_1_1_0")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_1_0)
        self.TXT_SKILL_1_1_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_1_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_1_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_1.setMaxLength(1)
        self.TXT_SKILL_1_1_1.setObjectName("TXT_SKILL_1_1_1")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_1_1)
        self.TXT_SKILL_1_1_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_1_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_1_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_1_2.setMaxLength(1)
        self.TXT_SKILL_1_1_2.setObjectName("TXT_SKILL_1_1_2")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_1_2)
        spacerItem4 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.TXT_SKILL_1_2_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_2_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_2_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_0.setMaxLength(1)
        self.TXT_SKILL_1_2_0.setObjectName("TXT_SKILL_1_2_0")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_2_0)
        self.TXT_SKILL_1_2_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_2_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_2_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_1.setMaxLength(1)
        self.TXT_SKILL_1_2_1.setObjectName("TXT_SKILL_1_2_1")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_2_1)
        self.TXT_SKILL_1_2_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_1_2_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_1_2_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_1_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_1_2_2.setMaxLength(1)
        self.TXT_SKILL_1_2_2.setObjectName("TXT_SKILL_1_2_2")
        self.horizontalLayout_7.addWidget(self.TXT_SKILL_1_2_2)
        spacerItem5 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.TXT_HOUGU_1_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_1_0.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_1_0.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_0.setMaxLength(1)
        self.TXT_HOUGU_1_0.setObjectName("TXT_HOUGU_1_0")
        self.horizontalLayout_7.addWidget(self.TXT_HOUGU_1_0)
        self.TXT_HOUGU_1_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_1_1.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_1_1.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_1_1.setMaxLength(1)
        self.TXT_HOUGU_1_1.setObjectName("TXT_HOUGU_1_1")
        self.horizontalLayout_7.addWidget(self.TXT_HOUGU_1_1)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(12, 24))
        self.label_4.setMaximumSize(QtCore.QSize(12, 24))
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.RBT_2 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBT_2.sizePolicy().hasHeightForWidth())
        self.RBT_2.setSizePolicy(sizePolicy)
        self.RBT_2.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_2.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_2.setText("")
        self.RBT_2.setObjectName("RBT_2")
        self.BTG_FRIEND.addButton(self.RBT_2)
        self.horizontalLayout_8.addWidget(self.RBT_2)
        self.TXT_SKILL_2_0_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_0_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_0_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_0.setMaxLength(1)
        self.TXT_SKILL_2_0_0.setObjectName("TXT_SKILL_2_0_0")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_0_0)
        self.TXT_SKILL_2_0_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_0_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_0_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_1.setMaxLength(1)
        self.TXT_SKILL_2_0_1.setObjectName("TXT_SKILL_2_0_1")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_0_1)
        self.TXT_SKILL_2_0_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_0_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_0_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_0_2.setMaxLength(1)
        self.TXT_SKILL_2_0_2.setObjectName("TXT_SKILL_2_0_2")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_0_2)
        spacerItem6 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.TXT_SKILL_2_1_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_1_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_1_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_0.setMaxLength(1)
        self.TXT_SKILL_2_1_0.setObjectName("TXT_SKILL_2_1_0")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_1_0)
        self.TXT_SKILL_2_1_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_1_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_1_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_1.setMaxLength(1)
        self.TXT_SKILL_2_1_1.setObjectName("TXT_SKILL_2_1_1")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_1_1)
        self.TXT_SKILL_2_1_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_1_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_1_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_1_2.setMaxLength(1)
        self.TXT_SKILL_2_1_2.setObjectName("TXT_SKILL_2_1_2")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_1_2)
        spacerItem7 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.TXT_SKILL_2_2_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_2_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_2_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_0.setMaxLength(1)
        self.TXT_SKILL_2_2_0.setObjectName("TXT_SKILL_2_2_0")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_2_0)
        self.TXT_SKILL_2_2_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_2_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_2_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_1.setMaxLength(1)
        self.TXT_SKILL_2_2_1.setObjectName("TXT_SKILL_2_2_1")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_2_1)
        self.TXT_SKILL_2_2_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_2_2_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_2_2_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_2_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_2_2_2.setMaxLength(1)
        self.TXT_SKILL_2_2_2.setObjectName("TXT_SKILL_2_2_2")
        self.horizontalLayout_8.addWidget(self.TXT_SKILL_2_2_2)
        spacerItem8 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.TXT_HOUGU_2_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_2_0.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_2_0.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_0.setMaxLength(1)
        self.TXT_HOUGU_2_0.setObjectName("TXT_HOUGU_2_0")
        self.horizontalLayout_8.addWidget(self.TXT_HOUGU_2_0)
        self.TXT_HOUGU_2_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_2_1.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_2_1.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_2_1.setMaxLength(1)
        self.TXT_HOUGU_2_1.setObjectName("TXT_HOUGU_2_1")
        self.horizontalLayout_8.addWidget(self.TXT_HOUGU_2_1)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(12, 24))
        self.label_5.setMaximumSize(QtCore.QSize(12, 24))
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.RBT_3 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBT_3.sizePolicy().hasHeightForWidth())
        self.RBT_3.setSizePolicy(sizePolicy)
        self.RBT_3.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_3.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_3.setText("")
        self.RBT_3.setObjectName("RBT_3")
        self.BTG_FRIEND.addButton(self.RBT_3)
        self.horizontalLayout_9.addWidget(self.RBT_3)
        self.TXT_SKILL_3_0_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_0_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_0_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_0.setMaxLength(1)
        self.TXT_SKILL_3_0_0.setObjectName("TXT_SKILL_3_0_0")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_0_0)
        self.TXT_SKILL_3_0_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_0_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_0_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_1.setMaxLength(1)
        self.TXT_SKILL_3_0_1.setObjectName("TXT_SKILL_3_0_1")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_0_1)
        self.TXT_SKILL_3_0_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_0_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_0_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_0_2.setMaxLength(1)
        self.TXT_SKILL_3_0_2.setObjectName("TXT_SKILL_3_0_2")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_0_2)
        spacerItem9 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.TXT_SKILL_3_1_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_1_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_1_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_0.setMaxLength(1)
        self.TXT_SKILL_3_1_0.setObjectName("TXT_SKILL_3_1_0")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_1_0)
        self.TXT_SKILL_3_1_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_1_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_1_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_1.setMaxLength(1)
        self.TXT_SKILL_3_1_1.setObjectName("TXT_SKILL_3_1_1")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_1_1)
        self.TXT_SKILL_3_1_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_1_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_1_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_1_2.setMaxLength(1)
        self.TXT_SKILL_3_1_2.setObjectName("TXT_SKILL_3_1_2")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_1_2)
        spacerItem10 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.TXT_SKILL_3_2_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_2_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_2_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_0.setMaxLength(1)
        self.TXT_SKILL_3_2_0.setObjectName("TXT_SKILL_3_2_0")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_2_0)
        self.TXT_SKILL_3_2_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_2_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_2_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_1.setMaxLength(1)
        self.TXT_SKILL_3_2_1.setObjectName("TXT_SKILL_3_2_1")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_2_1)
        self.TXT_SKILL_3_2_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_3_2_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_3_2_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_3_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_3_2_2.setMaxLength(1)
        self.TXT_SKILL_3_2_2.setObjectName("TXT_SKILL_3_2_2")
        self.horizontalLayout_9.addWidget(self.TXT_SKILL_3_2_2)
        spacerItem11 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.TXT_HOUGU_3_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_3_0.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_3_0.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_3_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_0.setMaxLength(1)
        self.TXT_HOUGU_3_0.setObjectName("TXT_HOUGU_3_0")
        self.horizontalLayout_9.addWidget(self.TXT_HOUGU_3_0)
        self.TXT_HOUGU_3_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_3_1.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_3_1.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_3_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_3_1.setMaxLength(1)
        self.TXT_HOUGU_3_1.setObjectName("TXT_HOUGU_3_1")
        self.horizontalLayout_9.addWidget(self.TXT_HOUGU_3_1)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(12, 24))
        self.label_6.setMaximumSize(QtCore.QSize(12, 24))
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.RBT_4 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBT_4.sizePolicy().hasHeightForWidth())
        self.RBT_4.setSizePolicy(sizePolicy)
        self.RBT_4.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_4.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBT_4.setText("")
        self.RBT_4.setChecked(True)
        self.RBT_4.setObjectName("RBT_4")
        self.BTG_FRIEND.addButton(self.RBT_4)
        self.horizontalLayout_10.addWidget(self.RBT_4)
        self.TXT_SKILL_4_0_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_0_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_0_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_0.setMaxLength(1)
        self.TXT_SKILL_4_0_0.setObjectName("TXT_SKILL_4_0_0")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_0_0)
        self.TXT_SKILL_4_0_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_0_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_0_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_1.setMaxLength(1)
        self.TXT_SKILL_4_0_1.setObjectName("TXT_SKILL_4_0_1")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_0_1)
        self.TXT_SKILL_4_0_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_0_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_0_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_0_2.setMaxLength(1)
        self.TXT_SKILL_4_0_2.setObjectName("TXT_SKILL_4_0_2")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_0_2)
        spacerItem12 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.TXT_SKILL_4_1_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_1_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_1_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_0.setMaxLength(1)
        self.TXT_SKILL_4_1_0.setObjectName("TXT_SKILL_4_1_0")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_1_0)
        self.TXT_SKILL_4_1_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_1_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_1_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_1.setMaxLength(1)
        self.TXT_SKILL_4_1_1.setObjectName("TXT_SKILL_4_1_1")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_1_1)
        self.TXT_SKILL_4_1_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_1_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_1_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_1_2.setMaxLength(1)
        self.TXT_SKILL_4_1_2.setObjectName("TXT_SKILL_4_1_2")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_1_2)
        spacerItem13 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.TXT_SKILL_4_2_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_2_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_2_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_0.setMaxLength(1)
        self.TXT_SKILL_4_2_0.setObjectName("TXT_SKILL_4_2_0")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_2_0)
        self.TXT_SKILL_4_2_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_2_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_2_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_1.setMaxLength(1)
        self.TXT_SKILL_4_2_1.setObjectName("TXT_SKILL_4_2_1")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_2_1)
        self.TXT_SKILL_4_2_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_4_2_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_4_2_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_4_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_4_2_2.setMaxLength(1)
        self.TXT_SKILL_4_2_2.setObjectName("TXT_SKILL_4_2_2")
        self.horizontalLayout_10.addWidget(self.TXT_SKILL_4_2_2)
        spacerItem14 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.TXT_HOUGU_4_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_4_0.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_4_0.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_4_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_0.setMaxLength(1)
        self.TXT_HOUGU_4_0.setObjectName("TXT_HOUGU_4_0")
        self.horizontalLayout_10.addWidget(self.TXT_HOUGU_4_0)
        self.TXT_HOUGU_4_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_4_1.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_4_1.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_4_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_4_1.setMaxLength(1)
        self.TXT_HOUGU_4_1.setObjectName("TXT_HOUGU_4_1")
        self.horizontalLayout_10.addWidget(self.TXT_HOUGU_4_1)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(12, 24))
        self.label_7.setMaximumSize(QtCore.QSize(12, 24))
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.RBT_5 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBT_5.sizePolicy().hasHeightForWidth())
        self.RBT_5.setSizePolicy(sizePolicy)
        self.RBT_5.setMinimumSize(QtCore.QSize(24, 24))
        self.RBT_5.setMaximumSize(QtCore.QSize(24, 24))
        self.RBT_5.setText("")
        self.RBT_5.setChecked(False)
        self.RBT_5.setObjectName("RBT_5")
        self.BTG_FRIEND.addButton(self.RBT_5)
        self.horizontalLayout_11.addWidget(self.RBT_5)
        self.TXT_SKILL_5_0_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_0_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_0_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_0_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_0.setMaxLength(1)
        self.TXT_SKILL_5_0_0.setObjectName("TXT_SKILL_5_0_0")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_0_0)
        self.TXT_SKILL_5_0_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_0_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_0_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_0_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_1.setMaxLength(1)
        self.TXT_SKILL_5_0_1.setObjectName("TXT_SKILL_5_0_1")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_0_1)
        self.TXT_SKILL_5_0_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_0_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_0_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_0_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_0_2.setMaxLength(1)
        self.TXT_SKILL_5_0_2.setObjectName("TXT_SKILL_5_0_2")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_0_2)
        spacerItem15 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.TXT_SKILL_5_1_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_1_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_1_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_1_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_0.setMaxLength(1)
        self.TXT_SKILL_5_1_0.setObjectName("TXT_SKILL_5_1_0")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_1_0)
        self.TXT_SKILL_5_1_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_1_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_1_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_1_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_1.setMaxLength(1)
        self.TXT_SKILL_5_1_1.setObjectName("TXT_SKILL_5_1_1")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_1_1)
        self.TXT_SKILL_5_1_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_1_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_1_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_1_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_1_2.setMaxLength(1)
        self.TXT_SKILL_5_1_2.setObjectName("TXT_SKILL_5_1_2")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_1_2)
        spacerItem16 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.TXT_SKILL_5_2_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_2_0.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_2_0.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_2_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_0.setMaxLength(1)
        self.TXT_SKILL_5_2_0.setObjectName("TXT_SKILL_5_2_0")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_2_0)
        self.TXT_SKILL_5_2_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_2_1.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_2_1.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_2_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_1.setMaxLength(1)
        self.TXT_SKILL_5_2_1.setObjectName("TXT_SKILL_5_2_1")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_2_1)
        self.TXT_SKILL_5_2_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_SKILL_5_2_2.sizePolicy().hasHeightForWidth())
        self.TXT_SKILL_5_2_2.setSizePolicy(sizePolicy)
        self.TXT_SKILL_5_2_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_SKILL_5_2_2.setMaxLength(1)
        self.TXT_SKILL_5_2_2.setObjectName("TXT_SKILL_5_2_2")
        self.horizontalLayout_11.addWidget(self.TXT_SKILL_5_2_2)
        spacerItem17 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.TXT_HOUGU_5_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_5_0.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_5_0.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_5_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_0.setMaxLength(1)
        self.TXT_HOUGU_5_0.setObjectName("TXT_HOUGU_5_0")
        self.horizontalLayout_11.addWidget(self.TXT_HOUGU_5_0)
        self.TXT_HOUGU_5_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_HOUGU_5_1.sizePolicy().hasHeightForWidth())
        self.TXT_HOUGU_5_1.setSizePolicy(sizePolicy)
        self.TXT_HOUGU_5_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_HOUGU_5_1.setMaxLength(1)
        self.TXT_HOUGU_5_1.setObjectName("TXT_HOUGU_5_1")
        self.horizontalLayout_11.addWidget(self.TXT_HOUGU_5_1)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout_2)
        self.LBL_DANGERPOS = QtWidgets.QLabel(self.centralwidget)
        self.LBL_DANGERPOS.setObjectName("LBL_DANGERPOS")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LBL_DANGERPOS)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.TXT_DANGER_0 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_DANGER_0.sizePolicy().hasHeightForWidth())
        self.TXT_DANGER_0.setSizePolicy(sizePolicy)
        self.TXT_DANGER_0.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_0.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_0.setMaxLength(1)
        self.TXT_DANGER_0.setObjectName("TXT_DANGER_0")
        self.horizontalLayout_6.addWidget(self.TXT_DANGER_0)
        spacerItem18 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.TXT_DANGER_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_DANGER_1.sizePolicy().hasHeightForWidth())
        self.TXT_DANGER_1.setSizePolicy(sizePolicy)
        self.TXT_DANGER_1.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_1.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_1.setMaxLength(1)
        self.TXT_DANGER_1.setObjectName("TXT_DANGER_1")
        self.horizontalLayout_6.addWidget(self.TXT_DANGER_1)
        spacerItem19 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem19)
        self.TXT_DANGER_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_DANGER_2.sizePolicy().hasHeightForWidth())
        self.TXT_DANGER_2.setSizePolicy(sizePolicy)
        self.TXT_DANGER_2.setMinimumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_DANGER_2.setMaxLength(1)
        self.TXT_DANGER_2.setObjectName("TXT_DANGER_2")
        self.horizontalLayout_6.addWidget(self.TXT_DANGER_2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.LBL_APPLE = QtWidgets.QLabel(self.centralwidget)
        self.LBL_APPLE.setObjectName("LBL_APPLE")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LBL_APPLE)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CBX_APPLE = QtWidgets.QComboBox(self.centralwidget)
        self.CBX_APPLE.setObjectName("CBX_APPLE")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.CBX_APPLE.addItem("")
        self.horizontalLayout_3.addWidget(self.CBX_APPLE)
        self.TXT_APPLE = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_APPLE.sizePolicy().hasHeightForWidth())
        self.TXT_APPLE.setSizePolicy(sizePolicy)
        self.TXT_APPLE.setMaxLength(10)
        self.TXT_APPLE.setObjectName("TXT_APPLE")
        self.horizontalLayout_3.addWidget(self.TXT_APPLE)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.TXT_ADDRESS = QtWidgets.QLineEdit(self.centralwidget)
        self.TXT_ADDRESS.setMaxLength(50)
        self.TXT_ADDRESS.setObjectName("TXT_ADDRESS")
        self.horizontalLayout_20.addWidget(self.TXT_ADDRESS)
        self.BTN_CONNECT = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_CONNECT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_CONNECT.setCheckable(False)
        self.BTN_CONNECT.setChecked(False)
        self.BTN_CONNECT.setObjectName("BTN_CONNECT")
        self.horizontalLayout_20.addWidget(self.BTN_CONNECT)
        self.BTN_DISCONNECT = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_DISCONNECT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_DISCONNECT.setObjectName("BTN_DISCONNECT")
        self.horizontalLayout_20.addWidget(self.BTN_DISCONNECT)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.BTN_GETDEVICE = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_GETDEVICE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_GETDEVICE.setObjectName("BTN_GETDEVICE")
        self.horizontalLayout_21.addWidget(self.BTN_GETDEVICE)
        self.CBX_DEVICE = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CBX_DEVICE.sizePolicy().hasHeightForWidth())
        self.CBX_DEVICE.setSizePolicy(sizePolicy)
        self.CBX_DEVICE.setEditable(True)
        self.CBX_DEVICE.setObjectName("CBX_DEVICE")
        self.horizontalLayout_21.addWidget(self.CBX_DEVICE)
        self.BTN_TESTDEVICE = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_TESTDEVICE.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_TESTDEVICE.sizePolicy().hasHeightForWidth())
        self.BTN_TESTDEVICE.setSizePolicy(sizePolicy)
        self.BTN_TESTDEVICE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_TESTDEVICE.setObjectName("BTN_TESTDEVICE")
        self.horizontalLayout_21.addWidget(self.BTN_TESTDEVICE)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BTN_GETHWND = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_GETHWND.setEnabled(True)
        self.BTN_GETHWND.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_GETHWND.setObjectName("BTN_GETHWND")
        self.verticalLayout_4.addWidget(self.BTN_GETHWND)
        self.BTN_CHECK = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_CHECK.setEnabled(True)
        self.BTN_CHECK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_CHECK.setObjectName("BTN_CHECK")
        self.verticalLayout_4.addWidget(self.BTN_CHECK)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BTN_DRAW = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_DRAW.setEnabled(False)
        self.BTN_DRAW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_DRAW.setObjectName("BTN_DRAW")
        self.verticalLayout.addWidget(self.BTN_DRAW)
        self.BTN_ONEBATTLE = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ONEBATTLE.sizePolicy().hasHeightForWidth())
        self.BTN_ONEBATTLE.setSizePolicy(sizePolicy)
        self.BTN_ONEBATTLE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_ONEBATTLE.setObjectName("BTN_ONEBATTLE")
        self.verticalLayout.addWidget(self.BTN_ONEBATTLE)
        self.BTN_MAIN = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_MAIN.sizePolicy().hasHeightForWidth())
        self.BTN_MAIN.setSizePolicy(sizePolicy)
        self.BTN_MAIN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_MAIN.setObjectName("BTN_MAIN")
        self.verticalLayout.addWidget(self.BTN_MAIN)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BTN_PAUSE = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_PAUSE.setEnabled(False)
        self.BTN_PAUSE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_PAUSE.setObjectName("BTN_PAUSE")
        self.verticalLayout_3.addWidget(self.BTN_PAUSE)
        self.BTN_STOP = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_STOP.setEnabled(False)
        self.BTN_STOP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_STOP.setObjectName("BTN_STOP")
        self.verticalLayout_3.addWidget(self.BTN_STOP)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.menuAbout.addAction(self.actiona)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.CBX_APPLE.setCurrentIndex(0)
        self.BTN_ONEBATTLE.clicked.connect(MainWindow.runOneBattle)
        self.BTN_MAIN.clicked.connect(MainWindow.runMain)
        self.BTN_CHECK.clicked.connect(MainWindow.checkCheck)
        self.BTN_GETHWND.clicked.connect(MainWindow.getHwnd)
        self.BTN_CONNECT.clicked.connect(MainWindow.adbConnect)
        self.BTN_GETDEVICE.clicked.connect(MainWindow.getDevice)
        self.BTN_DISCONNECT.clicked.connect(MainWindow.adbDisconnect)
        self.BTN_PAUSE.clicked.connect(MainWindow.pause)
        self.BTN_STOP.clicked.connect(MainWindow.stop)
        self.CBX_PARTY.activated['QString'].connect(MainWindow.loadParty)
        self.BTN_PARTYSAVE.clicked.connect(MainWindow.saveParty)
        self.BTN_PARTYRESET.clicked.connect(MainWindow.resetParty)
        self.BTN_PARTYDELETE.clicked.connect(MainWindow.deleteParty)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.RBT_0, self.RBT_1)
        MainWindow.setTabOrder(self.RBT_1, self.RBT_2)
        MainWindow.setTabOrder(self.RBT_2, self.RBT_3)
        MainWindow.setTabOrder(self.RBT_3, self.RBT_4)
        MainWindow.setTabOrder(self.RBT_4, self.RBT_5)
        MainWindow.setTabOrder(self.RBT_5, self.TXT_SKILL_0_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_0_0_0, self.TXT_SKILL_0_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_0_0_1, self.TXT_SKILL_0_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_0_0_2, self.TXT_SKILL_0_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_0_1_0, self.TXT_SKILL_0_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_0_1_1, self.TXT_SKILL_0_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_0_1_2, self.TXT_SKILL_0_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_0_2_0, self.TXT_SKILL_0_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_0_2_1, self.TXT_SKILL_0_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_0_2_2, self.TXT_SKILL_1_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_1_0_0, self.TXT_SKILL_1_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_1_0_1, self.TXT_SKILL_1_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_1_0_2, self.TXT_SKILL_1_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_1_1_0, self.TXT_SKILL_1_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_1_1_1, self.TXT_SKILL_1_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_1_1_2, self.TXT_SKILL_1_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_1_2_0, self.TXT_SKILL_1_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_1_2_1, self.TXT_SKILL_1_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_1_2_2, self.TXT_SKILL_2_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_2_0_0, self.TXT_SKILL_2_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_2_0_1, self.TXT_SKILL_2_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_2_0_2, self.TXT_SKILL_2_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_2_1_0, self.TXT_SKILL_2_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_2_1_1, self.TXT_SKILL_2_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_2_1_2, self.TXT_SKILL_2_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_2_2_0, self.TXT_SKILL_2_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_2_2_1, self.TXT_SKILL_2_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_2_2_2, self.TXT_SKILL_3_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_3_0_0, self.TXT_SKILL_3_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_3_0_1, self.TXT_SKILL_3_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_3_0_2, self.TXT_SKILL_3_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_3_1_0, self.TXT_SKILL_3_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_3_1_1, self.TXT_SKILL_3_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_3_1_2, self.TXT_SKILL_3_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_3_2_0, self.TXT_SKILL_3_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_3_2_1, self.TXT_SKILL_3_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_3_2_2, self.TXT_SKILL_4_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_4_0_0, self.TXT_SKILL_4_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_4_0_1, self.TXT_SKILL_4_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_4_0_2, self.TXT_SKILL_4_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_4_1_0, self.TXT_SKILL_4_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_4_1_1, self.TXT_SKILL_4_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_4_1_2, self.TXT_SKILL_4_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_4_2_0, self.TXT_SKILL_4_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_4_2_1, self.TXT_SKILL_4_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_4_2_2, self.TXT_SKILL_5_0_0)
        MainWindow.setTabOrder(self.TXT_SKILL_5_0_0, self.TXT_SKILL_5_0_1)
        MainWindow.setTabOrder(self.TXT_SKILL_5_0_1, self.TXT_SKILL_5_0_2)
        MainWindow.setTabOrder(self.TXT_SKILL_5_0_2, self.TXT_SKILL_5_1_0)
        MainWindow.setTabOrder(self.TXT_SKILL_5_1_0, self.TXT_SKILL_5_1_1)
        MainWindow.setTabOrder(self.TXT_SKILL_5_1_1, self.TXT_SKILL_5_1_2)
        MainWindow.setTabOrder(self.TXT_SKILL_5_1_2, self.TXT_SKILL_5_2_0)
        MainWindow.setTabOrder(self.TXT_SKILL_5_2_0, self.TXT_SKILL_5_2_1)
        MainWindow.setTabOrder(self.TXT_SKILL_5_2_1, self.TXT_SKILL_5_2_2)
        MainWindow.setTabOrder(self.TXT_SKILL_5_2_2, self.TXT_HOUGU_0_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_0_0, self.TXT_HOUGU_0_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_0_1, self.TXT_HOUGU_1_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_1_0, self.TXT_HOUGU_1_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_1_1, self.TXT_HOUGU_2_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_2_0, self.TXT_HOUGU_2_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_2_1, self.TXT_HOUGU_3_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_3_0, self.TXT_HOUGU_3_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_3_1, self.TXT_HOUGU_4_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_4_0, self.TXT_HOUGU_4_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_4_1, self.TXT_HOUGU_5_0)
        MainWindow.setTabOrder(self.TXT_HOUGU_5_0, self.TXT_HOUGU_5_1)
        MainWindow.setTabOrder(self.TXT_HOUGU_5_1, self.TXT_DANGER_0)
        MainWindow.setTabOrder(self.TXT_DANGER_0, self.TXT_DANGER_1)
        MainWindow.setTabOrder(self.TXT_DANGER_1, self.TXT_DANGER_2)
        MainWindow.setTabOrder(self.TXT_DANGER_2, self.CBX_APPLE)
        MainWindow.setTabOrder(self.CBX_APPLE, self.TXT_APPLE)
        MainWindow.setTabOrder(self.TXT_APPLE, self.TXT_ADDRESS)
        MainWindow.setTabOrder(self.TXT_ADDRESS, self.BTN_CONNECT)
        MainWindow.setTabOrder(self.BTN_CONNECT, self.BTN_DISCONNECT)
        MainWindow.setTabOrder(self.BTN_DISCONNECT, self.BTN_GETDEVICE)
        MainWindow.setTabOrder(self.BTN_GETDEVICE, self.CBX_DEVICE)
        MainWindow.setTabOrder(self.CBX_DEVICE, self.BTN_TESTDEVICE)
        MainWindow.setTabOrder(self.BTN_TESTDEVICE, self.BTN_DRAW)
        MainWindow.setTabOrder(self.BTN_DRAW, self.BTN_ONEBATTLE)
        MainWindow.setTabOrder(self.BTN_ONEBATTLE, self.BTN_MAIN)
        MainWindow.setTabOrder(self.BTN_MAIN, self.BTN_GETHWND)
        MainWindow.setTabOrder(self.BTN_GETHWND, self.BTN_CHECK)
        MainWindow.setTabOrder(self.BTN_CHECK, self.BTN_PAUSE)
        MainWindow.setTabOrder(self.BTN_PAUSE, self.BTN_STOP)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FGO script"))
        self.BTN_PARTYSAVE.setText(_translate("MainWindow", "保存"))
        self.BTN_PARTYRESET.setText(_translate("MainWindow", "重置"))
        self.BTN_PARTYDELETE.setText(_translate("MainWindow", "删除"))
        self.LBL_SKILLINFO.setText(_translate("MainWindow", "编队信息"))
        self.label_2.setText(_translate("MainWindow", "1"))
        self.TXT_SKILL_0_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_0_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_0_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_0_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_0_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_0_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_0_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_0_1.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "2"))
        self.TXT_SKILL_1_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_1_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_1_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_1_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_1_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_1_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_1_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_1_1.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "3"))
        self.TXT_SKILL_2_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_2_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_2_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_2_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_2_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_2_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_2_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_2_1.setText(_translate("MainWindow", "1"))
        self.label_5.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_3_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_3_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_3_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_3_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_3_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_3_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_3_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_3_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_3_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_3_1.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "5"))
        self.TXT_SKILL_4_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_4_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_4_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_4_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_4_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_4_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_4_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_4_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_4_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_4_1.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "6"))
        self.TXT_SKILL_5_0_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_0_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_5_0_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_0_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_0_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_0_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_1_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_1_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_5_1_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_1_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_1_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_1_2.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_2_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_2_0.setText(_translate("MainWindow", "4"))
        self.TXT_SKILL_5_2_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_2_1.setText(_translate("MainWindow", "0"))
        self.TXT_SKILL_5_2_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_SKILL_5_2_2.setText(_translate("MainWindow", "0"))
        self.TXT_HOUGU_5_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_5_0.setText(_translate("MainWindow", "1"))
        self.TXT_HOUGU_5_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_HOUGU_5_1.setText(_translate("MainWindow", "1"))
        self.LBL_DANGERPOS.setText(_translate("MainWindow", "优先攻击"))
        self.TXT_DANGER_0.setInputMask(_translate("MainWindow", "9"))
        self.TXT_DANGER_0.setText(_translate("MainWindow", "0"))
        self.TXT_DANGER_1.setInputMask(_translate("MainWindow", "9"))
        self.TXT_DANGER_1.setText(_translate("MainWindow", "0"))
        self.TXT_DANGER_2.setInputMask(_translate("MainWindow", "9"))
        self.TXT_DANGER_2.setText(_translate("MainWindow", "1"))
        self.LBL_APPLE.setText(_translate("MainWindow", "苹果"))
        self.CBX_APPLE.setItemText(0, _translate("MainWindow", "金"))
        self.CBX_APPLE.setItemText(1, _translate("MainWindow", "银"))
        self.CBX_APPLE.setItemText(2, _translate("MainWindow", "铜"))
        self.CBX_APPLE.setItemText(3, _translate("MainWindow", "彩"))
        self.TXT_APPLE.setText(_translate("MainWindow", "0"))
        self.TXT_ADDRESS.setText(_translate("MainWindow", "localhost:5555"))
        self.BTN_CONNECT.setText(_translate("MainWindow", "连接"))
        self.BTN_DISCONNECT.setText(_translate("MainWindow", "断开"))
        self.BTN_GETDEVICE.setText(_translate("MainWindow", "刷新"))
        self.BTN_TESTDEVICE.setText(_translate("MainWindow", "测试"))
        self.BTN_GETHWND.setText(_translate("MainWindow", "获取窗口句柄"))
        self.BTN_CHECK.setText(_translate("MainWindow", "检查截图"))
        self.BTN_DRAW.setText(_translate("MainWindow", "抽奖池"))
        self.BTN_ONEBATTLE.setText(_translate("MainWindow", "完成战斗"))
        self.BTN_MAIN.setText(_translate("MainWindow", "肝!"))
        self.BTN_PAUSE.setText(_translate("MainWindow", "挂起战斗"))
        self.BTN_STOP.setText(_translate("MainWindow", "终止战斗"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actiona.setText(_translate("MainWindow", "我还没想好这里应该写点啥"))
