# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fgoTeamupDialog.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QAbstractSpinBox, QApplication, QComboBox,
    QDialog, QDialogButtonBox, QFormLayout, QHBoxLayout,
    QLabel, QPushButton, QSizePolicy, QSpacerItem,
    QSpinBox, QVBoxLayout, QWidget)

class Ui_Teamup(object):
    def setupUi(self, Teamup):
        if not Teamup.objectName():
            Teamup.setObjectName(u"Teamup")
        Teamup.setStyleSheet(u"QWidget{font-family:\"Microsoft YaHei UI Light\";font-size:15px}")
        self.verticalLayout = QVBoxLayout(Teamup)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.LAYOUT_TEAM = QHBoxLayout()
        self.LAYOUT_TEAM.setObjectName(u"LAYOUT_TEAM")
        self.CBX_TEAM = QComboBox(Teamup)
        self.CBX_TEAM.setObjectName(u"CBX_TEAM")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CBX_TEAM.sizePolicy().hasHeightForWidth())
        self.CBX_TEAM.setSizePolicy(sizePolicy)
        self.CBX_TEAM.setMaxVisibleItems(17)

        self.LAYOUT_TEAM.addWidget(self.CBX_TEAM)

        self.BTN_SAVE = QPushButton(Teamup)
        self.BTN_SAVE.setObjectName(u"BTN_SAVE")
        self.BTN_SAVE.setCursor(QCursor(Qt.PointingHandCursor))

        self.LAYOUT_TEAM.addWidget(self.BTN_SAVE)

        self.BTN_RESET = QPushButton(Teamup)
        self.BTN_RESET.setObjectName(u"BTN_RESET")
        self.BTN_RESET.setCursor(QCursor(Qt.PointingHandCursor))

        self.LAYOUT_TEAM.addWidget(self.BTN_RESET)


        self.verticalLayout.addLayout(self.LAYOUT_TEAM)

        self.LAYOUT_INFO = QFormLayout()
        self.LAYOUT_INFO.setObjectName(u"LAYOUT_INFO")
        self.LAYOUT_INFO.setLabelAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.LBL_SKILLINFO = QLabel(Teamup)
        self.LBL_SKILLINFO.setObjectName(u"LBL_SKILLINFO")
        self.LBL_SKILLINFO.setMaximumSize(QSize(16777215, 28))

        self.LAYOUT_INFO.setWidget(0, QFormLayout.LabelRole, self.LBL_SKILLINFO)

        self.LAYOUT_INFO_TEAM = QFormLayout()
        self.LAYOUT_INFO_TEAM.setObjectName(u"LAYOUT_INFO_TEAM")
        self.LBL_TEAM_0 = QLabel(Teamup)
        self.LBL_TEAM_0.setObjectName(u"LBL_TEAM_0")
        self.LBL_TEAM_0.setMinimumSize(QSize(8, 25))
        self.LBL_TEAM_0.setMaximumSize(QSize(8, 25))
        self.LBL_TEAM_0.setAlignment(Qt.AlignCenter)

        self.LAYOUT_INFO_TEAM.setWidget(0, QFormLayout.LabelRole, self.LBL_TEAM_0)

        self.LAYOUT_INFO_TEAM_0 = QHBoxLayout()
        self.LAYOUT_INFO_TEAM_0.setObjectName(u"LAYOUT_INFO_TEAM_0")
        self.TXT_SKILL_0_0_0 = QSpinBox(Teamup)
        self.TXT_SKILL_0_0_0.setObjectName(u"TXT_SKILL_0_0_0")
        self.TXT_SKILL_0_0_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_0_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_0_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_0_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_0_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_0_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_0_0)

        self.TXT_SKILL_0_0_1 = QSpinBox(Teamup)
        self.TXT_SKILL_0_0_1.setObjectName(u"TXT_SKILL_0_0_1")
        self.TXT_SKILL_0_0_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_0_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_0_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_0_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_0_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_0_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_0_1)

        self.TXT_SKILL_0_0_2 = QSpinBox(Teamup)
        self.TXT_SKILL_0_0_2.setObjectName(u"TXT_SKILL_0_0_2")
        self.TXT_SKILL_0_0_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_0_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_0_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_0_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_0_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_0_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_0_2)

        self.TXT_SKILL_0_0_3 = QSpinBox(Teamup)
        self.TXT_SKILL_0_0_3.setObjectName(u"TXT_SKILL_0_0_3")
        self.TXT_SKILL_0_0_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_0_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_0_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_0_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_0_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_0_3.setMaximum(15)
        self.TXT_SKILL_0_0_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_0_3)

        self.SPACER_TEAM_0_0 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_0.addItem(self.SPACER_TEAM_0_0)

        self.TXT_SKILL_0_1_0 = QSpinBox(Teamup)
        self.TXT_SKILL_0_1_0.setObjectName(u"TXT_SKILL_0_1_0")
        self.TXT_SKILL_0_1_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_1_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_1_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_1_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_1_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_1_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_1_0)

        self.TXT_SKILL_0_1_1 = QSpinBox(Teamup)
        self.TXT_SKILL_0_1_1.setObjectName(u"TXT_SKILL_0_1_1")
        self.TXT_SKILL_0_1_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_1_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_1_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_1_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_1_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_1_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_1_1)

        self.TXT_SKILL_0_1_2 = QSpinBox(Teamup)
        self.TXT_SKILL_0_1_2.setObjectName(u"TXT_SKILL_0_1_2")
        self.TXT_SKILL_0_1_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_1_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_1_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_1_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_1_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_1_2)

        self.TXT_SKILL_0_1_3 = QSpinBox(Teamup)
        self.TXT_SKILL_0_1_3.setObjectName(u"TXT_SKILL_0_1_3")
        self.TXT_SKILL_0_1_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_1_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_1_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_1_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_1_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_1_3.setMaximum(15)
        self.TXT_SKILL_0_1_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_1_3)

        self.SPACER_TEAM_0_1 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_0.addItem(self.SPACER_TEAM_0_1)

        self.TXT_SKILL_0_2_0 = QSpinBox(Teamup)
        self.TXT_SKILL_0_2_0.setObjectName(u"TXT_SKILL_0_2_0")
        self.TXT_SKILL_0_2_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_2_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_2_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_2_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_2_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_2_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_2_0)

        self.TXT_SKILL_0_2_1 = QSpinBox(Teamup)
        self.TXT_SKILL_0_2_1.setObjectName(u"TXT_SKILL_0_2_1")
        self.TXT_SKILL_0_2_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_2_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_2_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_2_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_2_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_2_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_2_1)

        self.TXT_SKILL_0_2_2 = QSpinBox(Teamup)
        self.TXT_SKILL_0_2_2.setObjectName(u"TXT_SKILL_0_2_2")
        self.TXT_SKILL_0_2_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_2_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_2_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_2_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_2_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_2_2)

        self.TXT_SKILL_0_2_3 = QSpinBox(Teamup)
        self.TXT_SKILL_0_2_3.setObjectName(u"TXT_SKILL_0_2_3")
        self.TXT_SKILL_0_2_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_0_2_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_0_2_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_0_2_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_0_2_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_0_2_3.setMaximum(15)
        self.TXT_SKILL_0_2_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_SKILL_0_2_3)

        self.SPACER_TEAM_0_2 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_0.addItem(self.SPACER_TEAM_0_2)

        self.TXT_HOUGU_0_0 = QSpinBox(Teamup)
        self.TXT_HOUGU_0_0.setObjectName(u"TXT_HOUGU_0_0")
        self.TXT_HOUGU_0_0.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_0_0.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_0_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_0_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_0_0.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_HOUGU_0_0)

        self.TXT_HOUGU_0_1 = QSpinBox(Teamup)
        self.TXT_HOUGU_0_1.setObjectName(u"TXT_HOUGU_0_1")
        self.TXT_HOUGU_0_1.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_0_1.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_0_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_0_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_0_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_HOUGU_0_1.setMaximum(15)
        self.TXT_HOUGU_0_1.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_0.addWidget(self.TXT_HOUGU_0_1)


        self.LAYOUT_INFO_TEAM.setLayout(0, QFormLayout.FieldRole, self.LAYOUT_INFO_TEAM_0)

        self.LBL_TEAM_1 = QLabel(Teamup)
        self.LBL_TEAM_1.setObjectName(u"LBL_TEAM_1")
        self.LBL_TEAM_1.setMinimumSize(QSize(8, 25))
        self.LBL_TEAM_1.setMaximumSize(QSize(8, 25))
        self.LBL_TEAM_1.setAlignment(Qt.AlignCenter)

        self.LAYOUT_INFO_TEAM.setWidget(1, QFormLayout.LabelRole, self.LBL_TEAM_1)

        self.LBL_TEAM_2 = QLabel(Teamup)
        self.LBL_TEAM_2.setObjectName(u"LBL_TEAM_2")
        self.LBL_TEAM_2.setMinimumSize(QSize(8, 25))
        self.LBL_TEAM_2.setMaximumSize(QSize(8, 25))
        self.LBL_TEAM_2.setAlignment(Qt.AlignCenter)

        self.LAYOUT_INFO_TEAM.setWidget(2, QFormLayout.LabelRole, self.LBL_TEAM_2)

        self.LBL_TEAM_3 = QLabel(Teamup)
        self.LBL_TEAM_3.setObjectName(u"LBL_TEAM_3")
        self.LBL_TEAM_3.setMinimumSize(QSize(8, 25))
        self.LBL_TEAM_3.setMaximumSize(QSize(8, 25))
        self.LBL_TEAM_3.setAlignment(Qt.AlignCenter)

        self.LAYOUT_INFO_TEAM.setWidget(3, QFormLayout.LabelRole, self.LBL_TEAM_3)

        self.LBL_TEAM_4 = QLabel(Teamup)
        self.LBL_TEAM_4.setObjectName(u"LBL_TEAM_4")
        self.LBL_TEAM_4.setMinimumSize(QSize(8, 25))
        self.LBL_TEAM_4.setMaximumSize(QSize(8, 25))
        self.LBL_TEAM_4.setAlignment(Qt.AlignCenter)

        self.LAYOUT_INFO_TEAM.setWidget(4, QFormLayout.LabelRole, self.LBL_TEAM_4)

        self.LBL_TEAM_5 = QLabel(Teamup)
        self.LBL_TEAM_5.setObjectName(u"LBL_TEAM_5")
        self.LBL_TEAM_5.setMinimumSize(QSize(8, 25))
        self.LBL_TEAM_5.setMaximumSize(QSize(8, 25))
        self.LBL_TEAM_5.setAlignment(Qt.AlignCenter)

        self.LAYOUT_INFO_TEAM.setWidget(5, QFormLayout.LabelRole, self.LBL_TEAM_5)

        self.LAYOUT_INFO_TEAM_1 = QHBoxLayout()
        self.LAYOUT_INFO_TEAM_1.setObjectName(u"LAYOUT_INFO_TEAM_1")
        self.TXT_SKILL_1_0_0 = QSpinBox(Teamup)
        self.TXT_SKILL_1_0_0.setObjectName(u"TXT_SKILL_1_0_0")
        self.TXT_SKILL_1_0_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_0_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_0_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_0_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_0_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_0_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_0_0)

        self.TXT_SKILL_1_0_1 = QSpinBox(Teamup)
        self.TXT_SKILL_1_0_1.setObjectName(u"TXT_SKILL_1_0_1")
        self.TXT_SKILL_1_0_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_0_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_0_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_0_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_0_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_0_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_0_1)

        self.TXT_SKILL_1_0_2 = QSpinBox(Teamup)
        self.TXT_SKILL_1_0_2.setObjectName(u"TXT_SKILL_1_0_2")
        self.TXT_SKILL_1_0_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_0_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_0_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_0_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_0_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_0_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_0_2)

        self.TXT_SKILL_1_0_3 = QSpinBox(Teamup)
        self.TXT_SKILL_1_0_3.setObjectName(u"TXT_SKILL_1_0_3")
        self.TXT_SKILL_1_0_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_0_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_0_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_0_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_0_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_0_3.setMaximum(15)
        self.TXT_SKILL_1_0_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_0_3)

        self.SPACER_TEAM_1_0 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_1.addItem(self.SPACER_TEAM_1_0)

        self.TXT_SKILL_1_1_0 = QSpinBox(Teamup)
        self.TXT_SKILL_1_1_0.setObjectName(u"TXT_SKILL_1_1_0")
        self.TXT_SKILL_1_1_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_1_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_1_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_1_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_1_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_1_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_1_0)

        self.TXT_SKILL_1_1_1 = QSpinBox(Teamup)
        self.TXT_SKILL_1_1_1.setObjectName(u"TXT_SKILL_1_1_1")
        self.TXT_SKILL_1_1_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_1_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_1_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_1_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_1_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_1_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_1_1)

        self.TXT_SKILL_1_1_2 = QSpinBox(Teamup)
        self.TXT_SKILL_1_1_2.setObjectName(u"TXT_SKILL_1_1_2")
        self.TXT_SKILL_1_1_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_1_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_1_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_1_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_1_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_1_2)

        self.TXT_SKILL_1_1_3 = QSpinBox(Teamup)
        self.TXT_SKILL_1_1_3.setObjectName(u"TXT_SKILL_1_1_3")
        self.TXT_SKILL_1_1_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_1_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_1_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_1_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_1_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_1_3.setMaximum(15)
        self.TXT_SKILL_1_1_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_1_3)

        self.SPACER_TEAM_1_1 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_1.addItem(self.SPACER_TEAM_1_1)

        self.TXT_SKILL_1_2_0 = QSpinBox(Teamup)
        self.TXT_SKILL_1_2_0.setObjectName(u"TXT_SKILL_1_2_0")
        self.TXT_SKILL_1_2_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_2_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_2_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_2_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_2_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_2_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_2_0)

        self.TXT_SKILL_1_2_1 = QSpinBox(Teamup)
        self.TXT_SKILL_1_2_1.setObjectName(u"TXT_SKILL_1_2_1")
        self.TXT_SKILL_1_2_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_2_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_2_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_2_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_2_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_2_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_2_1)

        self.TXT_SKILL_1_2_2 = QSpinBox(Teamup)
        self.TXT_SKILL_1_2_2.setObjectName(u"TXT_SKILL_1_2_2")
        self.TXT_SKILL_1_2_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_2_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_2_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_2_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_2_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_2_2)

        self.TXT_SKILL_1_2_3 = QSpinBox(Teamup)
        self.TXT_SKILL_1_2_3.setObjectName(u"TXT_SKILL_1_2_3")
        self.TXT_SKILL_1_2_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_1_2_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_1_2_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_1_2_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_1_2_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_1_2_3.setMaximum(15)
        self.TXT_SKILL_1_2_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_SKILL_1_2_3)

        self.SPACER_TEAM_1_2 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_1.addItem(self.SPACER_TEAM_1_2)

        self.TXT_HOUGU_1_0 = QSpinBox(Teamup)
        self.TXT_HOUGU_1_0.setObjectName(u"TXT_HOUGU_1_0")
        self.TXT_HOUGU_1_0.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_1_0.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_1_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_1_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_1_0.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_HOUGU_1_0)

        self.TXT_HOUGU_1_1 = QSpinBox(Teamup)
        self.TXT_HOUGU_1_1.setObjectName(u"TXT_HOUGU_1_1")
        self.TXT_HOUGU_1_1.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_1_1.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_1_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_1_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_1_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_HOUGU_1_1.setMaximum(15)
        self.TXT_HOUGU_1_1.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_1.addWidget(self.TXT_HOUGU_1_1)


        self.LAYOUT_INFO_TEAM.setLayout(1, QFormLayout.FieldRole, self.LAYOUT_INFO_TEAM_1)

        self.LAYOUT_INFO_TEAM_2 = QHBoxLayout()
        self.LAYOUT_INFO_TEAM_2.setObjectName(u"LAYOUT_INFO_TEAM_2")
        self.TXT_SKILL_2_0_0 = QSpinBox(Teamup)
        self.TXT_SKILL_2_0_0.setObjectName(u"TXT_SKILL_2_0_0")
        self.TXT_SKILL_2_0_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_0_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_0_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_0_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_0_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_0_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_0_0)

        self.TXT_SKILL_2_0_1 = QSpinBox(Teamup)
        self.TXT_SKILL_2_0_1.setObjectName(u"TXT_SKILL_2_0_1")
        self.TXT_SKILL_2_0_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_0_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_0_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_0_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_0_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_0_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_0_1)

        self.TXT_SKILL_2_0_2 = QSpinBox(Teamup)
        self.TXT_SKILL_2_0_2.setObjectName(u"TXT_SKILL_2_0_2")
        self.TXT_SKILL_2_0_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_0_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_0_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_0_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_0_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_0_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_0_2)

        self.TXT_SKILL_2_0_3 = QSpinBox(Teamup)
        self.TXT_SKILL_2_0_3.setObjectName(u"TXT_SKILL_2_0_3")
        self.TXT_SKILL_2_0_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_0_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_0_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_0_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_0_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_0_3.setMaximum(15)
        self.TXT_SKILL_2_0_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_0_3)

        self.SPACER_TEAM_2_0 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_2.addItem(self.SPACER_TEAM_2_0)

        self.TXT_SKILL_2_1_0 = QSpinBox(Teamup)
        self.TXT_SKILL_2_1_0.setObjectName(u"TXT_SKILL_2_1_0")
        self.TXT_SKILL_2_1_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_1_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_1_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_1_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_1_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_1_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_1_0)

        self.TXT_SKILL_2_1_1 = QSpinBox(Teamup)
        self.TXT_SKILL_2_1_1.setObjectName(u"TXT_SKILL_2_1_1")
        self.TXT_SKILL_2_1_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_1_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_1_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_1_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_1_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_1_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_1_1)

        self.TXT_SKILL_2_1_2 = QSpinBox(Teamup)
        self.TXT_SKILL_2_1_2.setObjectName(u"TXT_SKILL_2_1_2")
        self.TXT_SKILL_2_1_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_1_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_1_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_1_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_1_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_1_2)

        self.TXT_SKILL_2_1_3 = QSpinBox(Teamup)
        self.TXT_SKILL_2_1_3.setObjectName(u"TXT_SKILL_2_1_3")
        self.TXT_SKILL_2_1_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_1_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_1_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_1_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_1_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_1_3.setMaximum(15)
        self.TXT_SKILL_2_1_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_1_3)

        self.SPACER_TEAM_2_1 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_2.addItem(self.SPACER_TEAM_2_1)

        self.TXT_SKILL_2_2_0 = QSpinBox(Teamup)
        self.TXT_SKILL_2_2_0.setObjectName(u"TXT_SKILL_2_2_0")
        self.TXT_SKILL_2_2_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_2_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_2_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_2_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_2_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_2_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_2_0)

        self.TXT_SKILL_2_2_1 = QSpinBox(Teamup)
        self.TXT_SKILL_2_2_1.setObjectName(u"TXT_SKILL_2_2_1")
        self.TXT_SKILL_2_2_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_2_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_2_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_2_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_2_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_2_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_2_1)

        self.TXT_SKILL_2_2_2 = QSpinBox(Teamup)
        self.TXT_SKILL_2_2_2.setObjectName(u"TXT_SKILL_2_2_2")
        self.TXT_SKILL_2_2_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_2_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_2_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_2_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_2_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_2_2)

        self.TXT_SKILL_2_2_3 = QSpinBox(Teamup)
        self.TXT_SKILL_2_2_3.setObjectName(u"TXT_SKILL_2_2_3")
        self.TXT_SKILL_2_2_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_2_2_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_2_2_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_2_2_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_2_2_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_2_2_3.setMaximum(15)
        self.TXT_SKILL_2_2_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_SKILL_2_2_3)

        self.SPACER_TEAM_2_2 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_2.addItem(self.SPACER_TEAM_2_2)

        self.TXT_HOUGU_2_0 = QSpinBox(Teamup)
        self.TXT_HOUGU_2_0.setObjectName(u"TXT_HOUGU_2_0")
        self.TXT_HOUGU_2_0.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_2_0.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_2_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_2_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_2_0.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_HOUGU_2_0)

        self.TXT_HOUGU_2_1 = QSpinBox(Teamup)
        self.TXT_HOUGU_2_1.setObjectName(u"TXT_HOUGU_2_1")
        self.TXT_HOUGU_2_1.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_2_1.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_2_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_2_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_2_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_HOUGU_2_1.setMaximum(15)
        self.TXT_HOUGU_2_1.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_2.addWidget(self.TXT_HOUGU_2_1)


        self.LAYOUT_INFO_TEAM.setLayout(2, QFormLayout.FieldRole, self.LAYOUT_INFO_TEAM_2)

        self.LAYOUT_INFO_TEAM_3 = QHBoxLayout()
        self.LAYOUT_INFO_TEAM_3.setObjectName(u"LAYOUT_INFO_TEAM_3")
        self.TXT_SKILL_3_0_0 = QSpinBox(Teamup)
        self.TXT_SKILL_3_0_0.setObjectName(u"TXT_SKILL_3_0_0")
        self.TXT_SKILL_3_0_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_0_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_0_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_0_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_0_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_0_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_0_0)

        self.TXT_SKILL_3_0_1 = QSpinBox(Teamup)
        self.TXT_SKILL_3_0_1.setObjectName(u"TXT_SKILL_3_0_1")
        self.TXT_SKILL_3_0_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_0_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_0_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_0_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_0_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_0_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_0_1)

        self.TXT_SKILL_3_0_2 = QSpinBox(Teamup)
        self.TXT_SKILL_3_0_2.setObjectName(u"TXT_SKILL_3_0_2")
        self.TXT_SKILL_3_0_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_0_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_0_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_0_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_0_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_0_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_0_2)

        self.TXT_SKILL_3_0_3 = QSpinBox(Teamup)
        self.TXT_SKILL_3_0_3.setObjectName(u"TXT_SKILL_3_0_3")
        self.TXT_SKILL_3_0_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_0_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_0_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_0_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_0_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_0_3.setMaximum(15)
        self.TXT_SKILL_3_0_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_0_3)

        self.SPACER_TEAM_3_0 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_3.addItem(self.SPACER_TEAM_3_0)

        self.TXT_SKILL_3_1_0 = QSpinBox(Teamup)
        self.TXT_SKILL_3_1_0.setObjectName(u"TXT_SKILL_3_1_0")
        self.TXT_SKILL_3_1_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_1_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_1_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_1_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_1_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_1_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_1_0)

        self.TXT_SKILL_3_1_1 = QSpinBox(Teamup)
        self.TXT_SKILL_3_1_1.setObjectName(u"TXT_SKILL_3_1_1")
        self.TXT_SKILL_3_1_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_1_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_1_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_1_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_1_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_1_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_1_1)

        self.TXT_SKILL_3_1_2 = QSpinBox(Teamup)
        self.TXT_SKILL_3_1_2.setObjectName(u"TXT_SKILL_3_1_2")
        self.TXT_SKILL_3_1_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_1_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_1_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_1_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_1_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_1_2)

        self.TXT_SKILL_3_1_3 = QSpinBox(Teamup)
        self.TXT_SKILL_3_1_3.setObjectName(u"TXT_SKILL_3_1_3")
        self.TXT_SKILL_3_1_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_1_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_1_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_1_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_1_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_1_3.setMaximum(15)
        self.TXT_SKILL_3_1_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_1_3)

        self.SPACER_TEAM_3_1 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_3.addItem(self.SPACER_TEAM_3_1)

        self.TXT_SKILL_3_2_0 = QSpinBox(Teamup)
        self.TXT_SKILL_3_2_0.setObjectName(u"TXT_SKILL_3_2_0")
        self.TXT_SKILL_3_2_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_2_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_2_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_2_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_2_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_2_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_2_0)

        self.TXT_SKILL_3_2_1 = QSpinBox(Teamup)
        self.TXT_SKILL_3_2_1.setObjectName(u"TXT_SKILL_3_2_1")
        self.TXT_SKILL_3_2_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_2_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_2_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_2_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_2_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_2_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_2_1)

        self.TXT_SKILL_3_2_2 = QSpinBox(Teamup)
        self.TXT_SKILL_3_2_2.setObjectName(u"TXT_SKILL_3_2_2")
        self.TXT_SKILL_3_2_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_2_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_2_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_2_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_2_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_2_2)

        self.TXT_SKILL_3_2_3 = QSpinBox(Teamup)
        self.TXT_SKILL_3_2_3.setObjectName(u"TXT_SKILL_3_2_3")
        self.TXT_SKILL_3_2_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_3_2_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_3_2_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_3_2_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_3_2_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_3_2_3.setMaximum(15)
        self.TXT_SKILL_3_2_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_SKILL_3_2_3)

        self.SPACER_TEAM_3_2 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_3.addItem(self.SPACER_TEAM_3_2)

        self.TXT_HOUGU_3_0 = QSpinBox(Teamup)
        self.TXT_HOUGU_3_0.setObjectName(u"TXT_HOUGU_3_0")
        self.TXT_HOUGU_3_0.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_3_0.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_3_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_3_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_3_0.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_HOUGU_3_0)

        self.TXT_HOUGU_3_1 = QSpinBox(Teamup)
        self.TXT_HOUGU_3_1.setObjectName(u"TXT_HOUGU_3_1")
        self.TXT_HOUGU_3_1.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_3_1.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_3_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_3_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_3_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_HOUGU_3_1.setMaximum(15)
        self.TXT_HOUGU_3_1.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_3.addWidget(self.TXT_HOUGU_3_1)


        self.LAYOUT_INFO_TEAM.setLayout(3, QFormLayout.FieldRole, self.LAYOUT_INFO_TEAM_3)

        self.LAYOUT_INFO_TEAM_4 = QHBoxLayout()
        self.LAYOUT_INFO_TEAM_4.setObjectName(u"LAYOUT_INFO_TEAM_4")
        self.TXT_SKILL_4_0_0 = QSpinBox(Teamup)
        self.TXT_SKILL_4_0_0.setObjectName(u"TXT_SKILL_4_0_0")
        self.TXT_SKILL_4_0_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_0_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_0_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_0_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_0_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_0_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_0_0)

        self.TXT_SKILL_4_0_1 = QSpinBox(Teamup)
        self.TXT_SKILL_4_0_1.setObjectName(u"TXT_SKILL_4_0_1")
        self.TXT_SKILL_4_0_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_0_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_0_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_0_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_0_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_0_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_0_1)

        self.TXT_SKILL_4_0_2 = QSpinBox(Teamup)
        self.TXT_SKILL_4_0_2.setObjectName(u"TXT_SKILL_4_0_2")
        self.TXT_SKILL_4_0_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_0_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_0_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_0_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_0_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_0_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_0_2)

        self.TXT_SKILL_4_0_3 = QSpinBox(Teamup)
        self.TXT_SKILL_4_0_3.setObjectName(u"TXT_SKILL_4_0_3")
        self.TXT_SKILL_4_0_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_0_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_0_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_0_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_0_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_0_3.setMaximum(15)
        self.TXT_SKILL_4_0_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_0_3)

        self.SPACER_TEAM_4_0 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_4.addItem(self.SPACER_TEAM_4_0)

        self.TXT_SKILL_4_1_0 = QSpinBox(Teamup)
        self.TXT_SKILL_4_1_0.setObjectName(u"TXT_SKILL_4_1_0")
        self.TXT_SKILL_4_1_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_1_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_1_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_1_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_1_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_1_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_1_0)

        self.TXT_SKILL_4_1_1 = QSpinBox(Teamup)
        self.TXT_SKILL_4_1_1.setObjectName(u"TXT_SKILL_4_1_1")
        self.TXT_SKILL_4_1_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_1_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_1_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_1_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_1_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_1_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_1_1)

        self.TXT_SKILL_4_1_2 = QSpinBox(Teamup)
        self.TXT_SKILL_4_1_2.setObjectName(u"TXT_SKILL_4_1_2")
        self.TXT_SKILL_4_1_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_1_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_1_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_1_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_1_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_1_2)

        self.TXT_SKILL_4_1_3 = QSpinBox(Teamup)
        self.TXT_SKILL_4_1_3.setObjectName(u"TXT_SKILL_4_1_3")
        self.TXT_SKILL_4_1_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_1_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_1_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_1_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_1_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_1_3.setMaximum(15)
        self.TXT_SKILL_4_1_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_1_3)

        self.SPACER_TEAM_4_1 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_4.addItem(self.SPACER_TEAM_4_1)

        self.TXT_SKILL_4_2_0 = QSpinBox(Teamup)
        self.TXT_SKILL_4_2_0.setObjectName(u"TXT_SKILL_4_2_0")
        self.TXT_SKILL_4_2_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_2_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_2_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_2_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_2_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_2_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_2_0)

        self.TXT_SKILL_4_2_1 = QSpinBox(Teamup)
        self.TXT_SKILL_4_2_1.setObjectName(u"TXT_SKILL_4_2_1")
        self.TXT_SKILL_4_2_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_2_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_2_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_2_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_2_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_2_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_2_1)

        self.TXT_SKILL_4_2_2 = QSpinBox(Teamup)
        self.TXT_SKILL_4_2_2.setObjectName(u"TXT_SKILL_4_2_2")
        self.TXT_SKILL_4_2_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_2_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_2_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_2_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_2_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_2_2)

        self.TXT_SKILL_4_2_3 = QSpinBox(Teamup)
        self.TXT_SKILL_4_2_3.setObjectName(u"TXT_SKILL_4_2_3")
        self.TXT_SKILL_4_2_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_4_2_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_4_2_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_4_2_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_4_2_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_4_2_3.setMaximum(15)
        self.TXT_SKILL_4_2_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_SKILL_4_2_3)

        self.SPACER_TEAM_4_2 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_4.addItem(self.SPACER_TEAM_4_2)

        self.TXT_HOUGU_4_0 = QSpinBox(Teamup)
        self.TXT_HOUGU_4_0.setObjectName(u"TXT_HOUGU_4_0")
        self.TXT_HOUGU_4_0.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_4_0.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_4_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_4_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_4_0.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_HOUGU_4_0)

        self.TXT_HOUGU_4_1 = QSpinBox(Teamup)
        self.TXT_HOUGU_4_1.setObjectName(u"TXT_HOUGU_4_1")
        self.TXT_HOUGU_4_1.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_4_1.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_4_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_4_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_4_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_HOUGU_4_1.setMaximum(15)
        self.TXT_HOUGU_4_1.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_4.addWidget(self.TXT_HOUGU_4_1)


        self.LAYOUT_INFO_TEAM.setLayout(4, QFormLayout.FieldRole, self.LAYOUT_INFO_TEAM_4)

        self.LAYOUT_INFO_TEAM_5 = QHBoxLayout()
        self.LAYOUT_INFO_TEAM_5.setObjectName(u"LAYOUT_INFO_TEAM_5")
        self.TXT_SKILL_5_0_0 = QSpinBox(Teamup)
        self.TXT_SKILL_5_0_0.setObjectName(u"TXT_SKILL_5_0_0")
        self.TXT_SKILL_5_0_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_0_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_0_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_0_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_0_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_0_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_0_0)

        self.TXT_SKILL_5_0_1 = QSpinBox(Teamup)
        self.TXT_SKILL_5_0_1.setObjectName(u"TXT_SKILL_5_0_1")
        self.TXT_SKILL_5_0_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_0_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_0_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_0_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_0_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_0_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_0_1)

        self.TXT_SKILL_5_0_2 = QSpinBox(Teamup)
        self.TXT_SKILL_5_0_2.setObjectName(u"TXT_SKILL_5_0_2")
        self.TXT_SKILL_5_0_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_0_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_0_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_0_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_0_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_0_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_0_2)

        self.TXT_SKILL_5_0_3 = QSpinBox(Teamup)
        self.TXT_SKILL_5_0_3.setObjectName(u"TXT_SKILL_5_0_3")
        self.TXT_SKILL_5_0_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_0_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_0_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_0_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_0_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_0_3.setMaximum(15)
        self.TXT_SKILL_5_0_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_0_3)

        self.SPACER_TEAM_5_0 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_5.addItem(self.SPACER_TEAM_5_0)

        self.TXT_SKILL_5_1_0 = QSpinBox(Teamup)
        self.TXT_SKILL_5_1_0.setObjectName(u"TXT_SKILL_5_1_0")
        self.TXT_SKILL_5_1_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_1_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_1_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_1_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_1_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_1_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_1_0)

        self.TXT_SKILL_5_1_1 = QSpinBox(Teamup)
        self.TXT_SKILL_5_1_1.setObjectName(u"TXT_SKILL_5_1_1")
        self.TXT_SKILL_5_1_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_1_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_1_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_1_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_1_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_1_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_1_1)

        self.TXT_SKILL_5_1_2 = QSpinBox(Teamup)
        self.TXT_SKILL_5_1_2.setObjectName(u"TXT_SKILL_5_1_2")
        self.TXT_SKILL_5_1_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_1_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_1_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_1_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_1_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_1_2)

        self.TXT_SKILL_5_1_3 = QSpinBox(Teamup)
        self.TXT_SKILL_5_1_3.setObjectName(u"TXT_SKILL_5_1_3")
        self.TXT_SKILL_5_1_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_1_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_1_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_1_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_1_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_1_3.setMaximum(15)
        self.TXT_SKILL_5_1_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_1_3)

        self.SPACER_TEAM_5_1 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_5.addItem(self.SPACER_TEAM_5_1)

        self.TXT_SKILL_5_2_0 = QSpinBox(Teamup)
        self.TXT_SKILL_5_2_0.setObjectName(u"TXT_SKILL_5_2_0")
        self.TXT_SKILL_5_2_0.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_2_0.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_2_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_2_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_2_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_2_0.setMaximum(9)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_2_0)

        self.TXT_SKILL_5_2_1 = QSpinBox(Teamup)
        self.TXT_SKILL_5_2_1.setObjectName(u"TXT_SKILL_5_2_1")
        self.TXT_SKILL_5_2_1.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_2_1.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_2_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_2_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_2_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_2_1.setMaximum(9)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_2_1)

        self.TXT_SKILL_5_2_2 = QSpinBox(Teamup)
        self.TXT_SKILL_5_2_2.setObjectName(u"TXT_SKILL_5_2_2")
        self.TXT_SKILL_5_2_2.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_2_2.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_2_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_2_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_2_2.setMaximum(3)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_2_2)

        self.TXT_SKILL_5_2_3 = QSpinBox(Teamup)
        self.TXT_SKILL_5_2_3.setObjectName(u"TXT_SKILL_5_2_3")
        self.TXT_SKILL_5_2_3.setMinimumSize(QSize(20, 25))
        self.TXT_SKILL_5_2_3.setMaximumSize(QSize(20, 25))
        self.TXT_SKILL_5_2_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_SKILL_5_2_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_SKILL_5_2_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_SKILL_5_2_3.setMaximum(15)
        self.TXT_SKILL_5_2_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_SKILL_5_2_3)

        self.SPACER_TEAM_5_2 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_TEAM_5.addItem(self.SPACER_TEAM_5_2)

        self.TXT_HOUGU_5_0 = QSpinBox(Teamup)
        self.TXT_HOUGU_5_0.setObjectName(u"TXT_HOUGU_5_0")
        self.TXT_HOUGU_5_0.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_5_0.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_5_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_5_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_5_0.setButtonSymbols(QAbstractSpinBox.NoButtons)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_HOUGU_5_0)

        self.TXT_HOUGU_5_1 = QSpinBox(Teamup)
        self.TXT_HOUGU_5_1.setObjectName(u"TXT_HOUGU_5_1")
        self.TXT_HOUGU_5_1.setMinimumSize(QSize(20, 25))
        self.TXT_HOUGU_5_1.setMaximumSize(QSize(20, 25))
        self.TXT_HOUGU_5_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_HOUGU_5_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_HOUGU_5_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_HOUGU_5_1.setMaximum(15)
        self.TXT_HOUGU_5_1.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_TEAM_5.addWidget(self.TXT_HOUGU_5_1)


        self.LAYOUT_INFO_TEAM.setLayout(5, QFormLayout.FieldRole, self.LAYOUT_INFO_TEAM_5)


        self.LAYOUT_INFO.setLayout(0, QFormLayout.FieldRole, self.LAYOUT_INFO_TEAM)

        self.LBL_MASTER = QLabel(Teamup)
        self.LBL_MASTER.setObjectName(u"LBL_MASTER")
        self.LBL_MASTER.setMaximumSize(QSize(16777215, 28))

        self.LAYOUT_INFO.setWidget(1, QFormLayout.LabelRole, self.LBL_MASTER)

        self.LAYOUT_INFO_MASTER = QHBoxLayout()
        self.LAYOUT_INFO_MASTER.setObjectName(u"LAYOUT_INFO_MASTER")
        self.TXT_MASTER_0_0 = QSpinBox(Teamup)
        self.TXT_MASTER_0_0.setObjectName(u"TXT_MASTER_0_0")
        self.TXT_MASTER_0_0.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_0_0.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_0_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_0_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_0_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_0_0.setMaximum(9)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_0_0)

        self.TXT_MASTER_0_1 = QSpinBox(Teamup)
        self.TXT_MASTER_0_1.setObjectName(u"TXT_MASTER_0_1")
        self.TXT_MASTER_0_1.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_0_1.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_0_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_0_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_0_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_0_1.setMaximum(9)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_0_1)

        self.TXT_MASTER_0_2 = QSpinBox(Teamup)
        self.TXT_MASTER_0_2.setObjectName(u"TXT_MASTER_0_2")
        self.TXT_MASTER_0_2.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_0_2.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_0_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_0_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_0_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_0_2.setMaximum(3)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_0_2)

        self.TXT_MASTER_0_3 = QSpinBox(Teamup)
        self.TXT_MASTER_0_3.setObjectName(u"TXT_MASTER_0_3")
        self.TXT_MASTER_0_3.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_0_3.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_0_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_0_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_0_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_0_3.setMaximum(15)
        self.TXT_MASTER_0_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_0_3)

        self.SPACER_MASTER_0 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_MASTER.addItem(self.SPACER_MASTER_0)

        self.TXT_MASTER_1_0 = QSpinBox(Teamup)
        self.TXT_MASTER_1_0.setObjectName(u"TXT_MASTER_1_0")
        self.TXT_MASTER_1_0.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_1_0.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_1_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_1_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_1_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_1_0.setMaximum(9)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_1_0)

        self.TXT_MASTER_1_1 = QSpinBox(Teamup)
        self.TXT_MASTER_1_1.setObjectName(u"TXT_MASTER_1_1")
        self.TXT_MASTER_1_1.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_1_1.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_1_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_1_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_1_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_1_1.setMaximum(9)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_1_1)

        self.TXT_MASTER_1_2 = QSpinBox(Teamup)
        self.TXT_MASTER_1_2.setObjectName(u"TXT_MASTER_1_2")
        self.TXT_MASTER_1_2.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_1_2.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_1_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_1_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_1_2.setMaximum(3)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_1_2)

        self.TXT_MASTER_1_3 = QSpinBox(Teamup)
        self.TXT_MASTER_1_3.setObjectName(u"TXT_MASTER_1_3")
        self.TXT_MASTER_1_3.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_1_3.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_1_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_1_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_1_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_1_3.setMaximum(15)
        self.TXT_MASTER_1_3.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_1_3)

        self.SPACER_MASTER_1 = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.LAYOUT_INFO_MASTER.addItem(self.SPACER_MASTER_1)

        self.TXT_MASTER_2_0 = QSpinBox(Teamup)
        self.TXT_MASTER_2_0.setObjectName(u"TXT_MASTER_2_0")
        self.TXT_MASTER_2_0.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_2_0.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_2_0.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_2_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_2_0.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_2_0.setMaximum(9)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_2_0)

        self.TXT_MASTER_2_1 = QSpinBox(Teamup)
        self.TXT_MASTER_2_1.setObjectName(u"TXT_MASTER_2_1")
        self.TXT_MASTER_2_1.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_2_1.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_2_1.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_2_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_2_1.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_2_1.setMaximum(9)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_2_1)

        self.TXT_MASTER_2_2 = QSpinBox(Teamup)
        self.TXT_MASTER_2_2.setObjectName(u"TXT_MASTER_2_2")
        self.TXT_MASTER_2_2.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_2_2.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_2_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_2_2.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_2_2.setMaximum(6)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_2_2)

        self.TXT_MASTER_2_3 = QSpinBox(Teamup)
        self.TXT_MASTER_2_3.setObjectName(u"TXT_MASTER_2_3")
        self.TXT_MASTER_2_3.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_2_3.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_2_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_2_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_2_3.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_2_3.setMaximum(6)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_2_3)

        self.TXT_MASTER_2_4 = QSpinBox(Teamup)
        self.TXT_MASTER_2_4.setObjectName(u"TXT_MASTER_2_4")
        self.TXT_MASTER_2_4.setMinimumSize(QSize(20, 25))
        self.TXT_MASTER_2_4.setMaximumSize(QSize(20, 25))
        self.TXT_MASTER_2_4.setContextMenuPolicy(Qt.NoContextMenu)
        self.TXT_MASTER_2_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.TXT_MASTER_2_4.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.TXT_MASTER_2_4.setMaximum(15)
        self.TXT_MASTER_2_4.setDisplayIntegerBase(16)

        self.LAYOUT_INFO_MASTER.addWidget(self.TXT_MASTER_2_4)


        self.LAYOUT_INFO.setLayout(1, QFormLayout.FieldRole, self.LAYOUT_INFO_MASTER)


        self.verticalLayout.addLayout(self.LAYOUT_INFO)

        self.buttonBox = QDialogButtonBox(Teamup)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)

        self.verticalLayout.addWidget(self.buttonBox)


        self.retranslateUi(Teamup)
        self.buttonBox.accepted.connect(Teamup.accept)
        self.buttonBox.rejected.connect(Teamup.reject)
        self.CBX_TEAM.textActivated.connect(Teamup.load)
        self.BTN_SAVE.clicked.connect(Teamup.save)
        self.BTN_RESET.clicked.connect(Teamup.reset)

        QMetaObject.connectSlotsByName(Teamup)
    # setupUi

    def retranslateUi(self, Teamup):
        Teamup.setWindowTitle(QCoreApplication.translate("Teamup", u"Teamup", None))
#if QT_CONFIG(statustip)
        self.CBX_TEAM.setStatusTip(QCoreApplication.translate("Teamup", u"\u9009\u53d6\u7f16\u961f,\u82e5\u9700\u65b0\u5efa\u6216\u5220\u9664\u8bf7\u76f4\u63a5\u66f4\u6539fgoTeamup.ini", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.BTN_SAVE.setStatusTip(QCoreApplication.translate("Teamup", u"\u4fdd\u5b58\u5f53\u524d\u7f16\u961f", None))
#endif // QT_CONFIG(statustip)
        self.BTN_SAVE.setText(QCoreApplication.translate("Teamup", u"\u4fdd\u5b58", None))
#if QT_CONFIG(statustip)
        self.BTN_RESET.setStatusTip(QCoreApplication.translate("Teamup", u"\u521d\u59cb\u5316\u5f53\u524d\u7f16\u961f,\u9700\u8981\u624b\u52a8\u4fdd\u5b58", None))
#endif // QT_CONFIG(statustip)
        self.BTN_RESET.setText(QCoreApplication.translate("Teamup", u"\u91cd\u7f6e", None))
        self.LBL_SKILLINFO.setText(QCoreApplication.translate("Teamup", u"\u7f16\u961f\u4fe1\u606f", None))
        self.LBL_TEAM_0.setText(QCoreApplication.translate("Teamup", u"1", None))
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_0_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_0_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_0_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_0_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_1_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_1_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_1_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_1_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_2_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_2_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_2_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_0_2_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_0_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u5b9d\u5177\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u5b9d\u5177", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_0_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
        self.LBL_TEAM_1.setText(QCoreApplication.translate("Teamup", u"2", None))
        self.LBL_TEAM_2.setText(QCoreApplication.translate("Teamup", u"3", None))
        self.LBL_TEAM_3.setText(QCoreApplication.translate("Teamup", u"4", None))
        self.LBL_TEAM_4.setText(QCoreApplication.translate("Teamup", u"5", None))
        self.LBL_TEAM_5.setText(QCoreApplication.translate("Teamup", u"6", None))
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_0_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_0_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_0_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_0_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_1_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_1_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_1_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_1_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_2_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_2_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_2_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_1_2_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_1_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u5b9d\u5177\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u5b9d\u5177", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_1_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_0_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_0_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_0_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_0_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_1_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_1_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_1_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_1_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_2_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_2_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_2_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_2_2_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_2_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u5b9d\u5177\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u5b9d\u5177", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_2_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_0_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_0_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_0_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_0_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_1_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_1_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_1_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_1_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_2_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_2_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_2_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_3_2_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_3_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u5b9d\u5177\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u5b9d\u5177", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_3_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_0_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_0_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_0_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_0_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_1_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_1_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_1_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_1_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_2_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_2_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_2_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_4_2_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_4_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u5b9d\u5177\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u5b9d\u5177", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_4_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_0_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_0_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_0_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_0_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_1_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_1_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_1_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_1_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_2_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_2_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u6700\u5c0f\u4f7f\u7528\u573a\u6b21\u7684\u6700\u5c0f\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_2_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_SKILL_5_2_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_5_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u5b9d\u5177\u7684\u6700\u5c0f\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u5b9d\u5177", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_HOUGU_5_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
        self.LBL_MASTER.setText(QCoreApplication.translate("Teamup", u"\u5fa1\u4e3b\u6280\u80fd", None))
#if QT_CONFIG(statustip)
        self.TXT_MASTER_0_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_0_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u4f7f\u7528\u573a\u6b21\u7684\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_0_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_0_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_1_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_1_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u4f7f\u7528\u573a\u6b21\u7684\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_1_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_1_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_2_0.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u4f7f\u7528\u573a\u6b21,0\u4e3a\u4e0d\u4f7f\u7528\u6280\u80fd", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_2_1.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u5728\u4f7f\u7528\u573a\u6b21\u7684\u4f7f\u7528\u56de\u5408", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_2_2.setStatusTip(QCoreApplication.translate("Teamup", u"\u6280\u80fd\u7684\u76ee\u6807,\u4ece\u5de6\u5f80\u53f31-3,0\u4e3a\u4e0d\u5173\u5fc3\u76ee\u6807", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_2_3.setStatusTip(QCoreApplication.translate("Teamup", u"\u4ec5\u7528\u4e8e\u6362\u4eba\u793c\u88c5,\u7f16\u961f\u754c\u9762\u4ece\u5de6\u5230\u53f31-6,\u975e\u6362\u4eba\u793c\u88c5\u586b0", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.TXT_MASTER_2_4.setStatusTip(QCoreApplication.translate("Teamup", u"\u4f18\u5148\u7ea7,\u8d8a\u5c0f\u8d8a\u4f18\u5148", None))
#endif // QT_CONFIG(statustip)
    # retranslateUi

